### ISSUE TITLE
Wrong search pattern in RegEx Example 3

### ISSUE THREAD

**Issue by Medvedishce** [notepad-plus-plus/npp-usermanual#102]
[https://npp-user-manual.org/docs/searching/#example-3](url)

There stated:

> Search `^(?=.)$`
> Replace with `file:///`
> Click **Replace all**
> This adds file:/// to the beginning of all non-empty lines
> 

This pattern not working, proper pattern wold be `^(?=.+$)`

**Comment by pryrt** [comment]
Actually, the intended search was `^(?=.)` without the end-of-line indicator.
