### ISSUE TITLE
npp-user-manual.org is down

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#115]
@donho ,

last night, I couldn't access npp-user-manual.org from home.  This morning, I tried from the office, and it's still not responding.  When I plug the URL into some of the online "is it down for everyone sites", it shows as down, too.
* https://downforeveryoneorjustme.com/npp-user-manual.org?proto=https
* https://www.isitdownrightnow.com/npp-user-manual.org.html

**Comment by donho** [comment]
Solved (by restart the PC).
Thank you for your heads up @pryrt
