### ISSUE TITLE
No documentation on the View > Project feature

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#131]
Per Alan's [discussion in the forum](https://community.notepad-plus-plus.org/topic/20302/notepad-projects-info), the manual seems to not include any documentation on the "Project" feature.

**Comment by pryrt** [comment]
I did some quick searches, and found that the old NppWiki _did_ have a page on Project Management, so I pulled up my archived copy of the old docs: that looks like a good starting point.  I will try to rework that page into something that works in the new manual

**Comment by donho** [comment]
Oups! "We" have forgotten this feature :)
@pryrt Feel free to add a page for this feature. Please let me know if you need help.
