### ISSUE TITLE
Typo in the section on Extended Search

### ISSUE THREAD

**Issue by Daksol** [notepad-plus-plus/npp-usermanual#156]
Typographical error in Search, Extended Search - see screenshot
https://npp-user-manual.org/docs/searching/#extended-search-mode

![npperror](https://user-images.githubusercontent.com/42010857/106361308-89adc400-631d-11eb-8941-9106eac41aad.PNG)

**Comment by pryrt** [comment]
Technically, `0x05C` is the same number as `0x5C` ... but for consistency, it should just be two digits like the others.  I have updated the source with commit 17d675e , so the next time the docs are published, that will be updated in the website, too.
