### ISSUE TITLE
I want hot key still useable when npp lose its focus

### ISSUE THREAD

**Issue by zhwandzcx** [notepad-plus-plus/npp-usermanual#162]
situation:  when i use three pc monitors, coding and doc and webpage are in different monitor.
if i want to page down  npp content, i have to alt +tab to npp to make it on focus, then i can press pageDown  or up.
i want npp official developers to add lose-focus-still-useable-hotKeys for npp.
thanks a lot.
you made world a better place

**Comment by zhwandzcx** [comment]
it may named global hotkey

**Comment by pryrt** [comment]
This repository and issues tracker is just for npp-user-manual.org documentation , not for feature requests for the Notepad++ application itself.  The application has a [separate issues tracker](/notepad-plus-plus/notepad-plus-plus/issues), so if you would like to request a feature, you need to ask over there.
