### ISSUE TITLE
Installer Command Line Options

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#164]
In the Community Forum, we've occasionally been asked to answer questions about, or show documentation for, the installer command-line options (for example, [here](https://community.notepad-plus-plus.org/topic/20777/install-command-line-parameters/2?_=1614714653378_)).  

In that thread, I assumed that Notepad++ uses the "NSIS" installer system, based on some text I found in the source code... but I'm not an expert on installer systems (ie, I know virtually nothing), so I don't want to provide false information.  But if I can get confirmation that we use NSIS, then I was thinking I would add  a section (probably on the command-prompt page, or maybe in the "Installer" section of the getting-started page) saying the officially-supported command-line options per https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers , just so we've got an "official" source to point such inquiries at.

My thought on phrasing would be something like, 
> The installer application accepts the [three NSIS command-line options](https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers):
> * `/S` : silent installation
> * `/D=c:\blah` or `/D=c:\path with spaces\blah` : overrides the default installation directory.  Must be the last argument on the installer command line.  Do _not_ put quotes around the path, even when there are spaces.
> * `/NCRC`: skips the installer's CRC check

So could one of the other notepad-user-manual-admin who knows more about the installer confirm whether "NSIS" is the correct installer type.  And any comments as to whether you think this belongs in our manual would be good, too.

**Comment by chcg** [comment]
Yes, NSIS is used, see e.g. https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/packageAll.bat#L296-L297
