### ISSUE TITLE
Add information about "Find in Projects" tab of Find dialog

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/npp-usermanual#166]
PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9534 and commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/5c884a80c676ad6172f1afa5de88a67c1c503df4 added a "Find in Projects" feature.

The way this feature works needs to be documented in the user manual.

**Comment by Uhf7** [comment]
> Can you provide user manual updates for the feature you've added? (from https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9534#issuecomment-791458597)

Yes, I think I can. It will take some days, because I have to begin with building the local test site.

**Comment by sasumner** [comment]
Bump.  Since this issue was opened, the N++ 7.9.4 RC has appeared, thus perhaps adding some increased desire to have a nice timing sync between actual 7.9.4 release and the manual being updated.

**Comment by Uhf7** [comment]
Yes, I'm on it, Hugo works, but it is quite much to read before I can really extend it. I plan a PR for it tomorrow.
