### ISSUE TITLE
Inaccuracy in "Replace All"

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#178]
See discussion in [forum: "New Line every n characters"](https://community.notepad-plus-plus.org/topic/20916/)

Basically, manual says "Replace All: Replaces all matches from the active location onward (following the Backward direction and Wrap around settings as appropriate)."  But it appears that "wrap around" being checked will change the behavior subtley.

```
one two three four five
fourteen something fifteen
```
* FIND = `(?i-s)\b((?<!☺ )f\w+)`
* REPLACE = `${1}☺`

(so it will only replace words starting with "f" that don't have smiley-space before it)

Put the cursor between `four` and `five`.  

If wrap-around is disabled, then **Replace All** will result in
```
one two three four five☺
fourteen☺ something fifteen☺
```
... which means the search really did start between the `four` and the `five`.   This is the behavior I expected.

But with wrap-around enabled, then **Replace All** will result in
```
one two three four☺ five
fourteen☺ something fifteen☺
```
... which says that the search must have started at the beginning of the file, rather than starting between `four` and `five`.  This surprised me, and seems to contradict the phrasing in the manual.

@sasumner , can you (or someone else familar with the codebase) confirm that wrap-around really does cause it to start from the beginning of the file for the global replacement?

**Comment by sasumner** [comment]
>can you ... confirm that wrap-around really does cause it to start from the beginning of the file for the global replacement?

This is something that @guy038 and I had a discussion about several years ago on the Community (see below).
I'm surprised that it isn't more well-known by now.

Yes, a _Replace All_ with _Wrap around_ ticked makes one-pass through the active document, from the very top to the very bottom.
A _Replace All_ with _Wrap around_ unticked searches from the caret in the indicated direction (controlled by _Backward direction_) to the respective end/beginning of file, and stops.

The following contains the requested source code analysis for this, I believe:

https://community.notepad-plus-plus.org/post/27911

Let me know if that is not sufficient for what you're requesting @pryrt .

BTW, Guy presents a nice "functionality table" [HERE](https://community.notepad-plus-plus.org/post/27946).
Perhaps something like this could be included in the manual?
Guy has made several of these types of tables over the years; I would like to see more of them included in the manual.  What do you think, @pryrt ?
I think there was a similar table that also explained window-flashing behavior on unsuccessful search and or wrap-around-happened -- that could be a valuable manual addition as well.

**Comment by sasumner** [comment]
### Very much a side note:

#### Github display of @pryrt 's "smiley" demo:

![image](https://user-images.githubusercontent.com/30118311/111867549-228ab400-894b-11eb-9ded-3407947f203c.png)

#### is way less effectual than what I saw in the gmail version:

![image](https://user-images.githubusercontent.com/30118311/111867564-3b936500-894b-11eb-9d6c-a87c3606769c.png)

**Comment by pryrt** [comment]
> I'm surprised that it isn't more well-known by now.

 For me, if it hasn't affected me personally, I'm apt to forget quirks like that, even if Guy or others talk about it in-depth on the forum.

> Yes, a Replace All with Wrap around ticked makes one-pass through the active document, from the very top to the very bottom.  A Replace All with Wrap around unticked searches from the caret in the indicated direction (controlled by Backward direction) to the respective end/beginning of file, and stops.

I think I am going to steal that phrasing (or nearly so) for the Manual.  And add in Guy's table.

> Guy has made several of these types of tables over the years; I would like to see more of them included in the manual. 

Sounds reasonable to me.

> Github display of @pryrt 's "smiley" demo is way less effectual than what I saw in the gmail version.  

Apparently.  In general, I tend to like the fonts that display emoji more similarly to the rest of the text (so the "github") version... but in situations like this, the more "loud emoji" does tend to help it stand out.

(After re-reading the mentioned forum thread -- which I only came to hours after the fact -- I see that both Alan and Guy had much simpler examples that could have proven the same thing.  But since you and Guy already knew about the problem, I guess proof wasn't actually necessary... other than to convince me.)
