### ISSUE TITLE
Update -qt command line

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/npp-usermanual#183]
I didn't even notice when, but the syntax for `-qt` has changed. Now it should be `-qt="some text"`.  In addition, I just don't know how to use " inside "".
https://npp-user-manual.org/docs/command-prompt/
https://npp-user-manual.org/docs/ghost-typing/

Edit: same for `-qn` and `qf`.

![image](https://user-images.githubusercontent.com/2730894/112722264-bd196300-8f08-11eb-9998-ca0cc980b0b4.png)

**Comment by sasumner** [comment]
>-qf

You wouldn't ever need/use `"` inside the `"..."` wrapper on this one.

I can't see any dev except @donho bothering to work on this one.

**Comment by ArkadiuszMichalski** [comment]
>You wouldn't ever need/use " inside the "..." wrapper on this one.

We can always enter data from a file by `-qf`  (if someone really wants it).
