### ISSUE TITLE
release npp-user-manual.org for v7.9.5

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#188]
@donho,

Did you want to release a copy of the npp-user-manual.org website to match the v7.9.5 application release?  As far as I can tell, we've documented everything that was new to v7.9.5.  You often do the new usermanual release shortly after setting a version for auto-update... and you set v7.9.5 to auto-update a couple days ago, so I thought I'd ping you to ask.

Also, I have seen that @sasumner has started submitting PR to update the manual for the future v7.9.6 -- which is great, and proactive, and I appreciate -- but I think we'd want to release the website that matches v7.9.5 before we incorporate any v7.9.6 documentation in the github.

This tag-for-release would also serve as a final proof of the new github action for adding the zipped usermanual asset when you tag the usermanual for release.

**Comment by donho** [comment]
OK, thank you for your heads up @pryrt . I'll do it tomorrow.

**Comment by donho** [comment]
@pryrt 
I just saw the new added link for downloading offline user manual. The link is invalid because it points to nothing so far.
I've also seem the argument in both https://github.com/notepad-plus-plus/npp-usermanual/commit/b44e48c950e8b5e2a92679b4dc58e1cc62ad6730 & https://github.com/notepad-plus-plus/npp-usermanual/commit/326eddd6de806fc34d4355db1795c7b51a18cdd3 for the format of link. 

Before we release this version, there are 3 points we should talk for this issue:
1. With what we should use to generate the offline user manual?
2. Where should be located the offline user manual in zip format? (in Github or in npp-user-manual.org)
3. Which look for the download offline document link?

It's important to review these above points before release, or we can always revert this part and take down the link for this release - I can do the release this evening and we can take our time for discussing these 3 points above?

Sorry that I wasn't available completely for the discussion about this issue. Could you point me out the tread of this issue please?

**Comment by pryrt** [comment]
@donho ,

> 1. With what we should use to generate the offline user manual?

The GitHub actions automatically create the zipfile, using the httrack utility that you suggested.  It does it in two stages:
1. When anyone does a push or pull, the [CI_Build](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/.github/workflows/CI_build.yml) action does the conversion, and attaches it as an "artifact" to the build.  This can be used for debugging the zipfile.
2. When you (@donho) create a new tag release, the [onTag_zip_manual_as_asset](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/.github/workflows/onTag_zip_manual_as_asset.yml) action will create a zipfile, but instead of making it an "artifact", it will make it an "asset", so it will show up as a third "asset" in the "assets" section of the github release page: 
![image](https://user-images.githubusercontent.com/17455758/113317677-76d75180-92c4-11eb-9e43-9018825c9fa1.png)
-- it would be a third, alongside the source code files.  
    * That asset can be referred to by a unique URL for each release -- but that means that we'd have to know beforehand what that release would be called, and then manually change the source every time before the release to point to the new URL.  That's not a good option for the URL to put in the source code
    * The asset for the most recent release tag has a generic URL, which is the https://github.com/notepad-plus-plus/npp-usermanual/releases/latest/download/nppUserManual.zip that is in the source code of the website now -- every time you do a new release, that URL will point to the most recent zipfile.  But until you create the first tag now that the action exists, that file will not exist.  As I said [here](https://github.com/notepad-plus-plus/npp-usermanual/pull/177#issuecomment-803437250), I could manually upload a zipfile to make the URL exist even now.  But as soon as you make a new tag, the URL will point to the automatically-created zipfile for the most recent tag.

> 2. Where should be located the offline user manual in zip format? (in Github or in npp-user-manual.org)

I personally think GitHub is the easiest.  First, because I've already got everything set up to work that way. ;-)  Second, I think if it is both something derived from the source code, and something that lives in the source code to then be distributed to the npp-user-manual.org website, it will get confusing/complicated to handle it.

> 3. Which look for the download offline document link?

I had originally tried to make it fancy (in 326eddd) -- but with that formatting, the httrack didn't see the link at all.  Thus, I changed it (in b44e48c) to be a standard inline link.  In theory, I could just make a "download" image, and make that image the link... but really, the standard inline text link should be sufficient -- all the other links in the usermanual website are done that way, after all.

**Comment by donho** [comment]
@pryrt 

Very nice job for point 1 & 2 - so it's all automated.

For the point 3, I have no problem to generate the link:

![image](https://user-images.githubusercontent.com/90293/113351374-120b0e00-933b-11eb-9517-9db802761b97.png)

with the following code:
```
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>

    <a href="https://github.com/notepad-plus-plus/npp-usermanual/releases/latest/download/nppUserManual.zip" style="
        text-align: center;
        font-size: larger;
        -moz-border-radius: 1em;
        border-radius: 1em;
        border: 1px solid #00A2E8;
        background-color: white;
        color: #00A2E8;
        padding: 2px 1em;
    ">Download offline User Manual</a>
</p>
```

Personally, I prefer this version, because it's more proper & clean - not too many stuffs to read.
Besides the link generation, do we have other impact for this solution?

**Comment by donho** [comment]
Here is the CLI command I use on my PC:
`C:\Program Files\WinHTTrack>httrack.exe "http://127.0.0.1:1313/" -O "c:\tmp\httrack_output"`

It does generate the link for downloading zip package.

My WinHttrack is downloaded here:
https://download.httrack.com/cserv.php3?File=httrack_x64.exe

**Comment by donho** [comment]
@pryrt 
Thank you for the new commit.
So is it OK for you to use the your 1st version of link?

**Comment by pryrt** [comment]
@donho ,

Sorry, not quite yet.  There's still some discrepancy between what happens with a local httrack and what happens in the automated one inside the GitHub action environment.

I have one more thing I want to try... but as a backup plan, I can make it work right in both environments if I change the main _index.md to _index.html and use HTML as the source of that first page in the website.  But I don't want to use that route unless I have to.

**Comment by donho** [comment]
@pryrt 
Thank you for your explanation.
Please let me know when it's ready so I will create the tag for triggering the automation (which is really neat).

**Comment by pryrt** [comment]
Okay, @donho , I have got the updated version merged into the master repo.  The link looks good now, even in the zipfile.

It's ready for you to tag.

**Comment by donho** [comment]
@pryrt 
Thank you
But... is the change of extension really necessary (`_index.md` to `_index.html`) ?

**Comment by pryrt** [comment]
@donho,

Sorry, it was the best I could get to work.  If I didn't change to .html as the source for that file, the hugo+httrack combination that's available to the GitHub Action server would just ignore the embedded HTML in the .md file, and the resulting zipfile HTML did not have the link at all.  (I don't know why it behaves differently on the GitHub Action compared to when you try it manually on your computer.)

Since changing the source file to .html gets the right result everywhere, I thought that was the best path forward.  It's just for that one file.

It is up to you whether to go forward with it as is.

**Comment by donho** [comment]
What's the version of hugo on GitHub?
I use `hugo.exe server -Debug`, it works fine.
`

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/npp-usermanual/blob/master/.github/workflows/CI_build.yml#L16

So it uses the latest version from
https://community.chocolatey.org/packages/hugo-extended
Hugo Extended 0.82.0 (https://github.com/gohugoio/hugo/releases/tag/v0.82.0)

https://community.chocolatey.org/packages/httrack
HTTrack 3.49.2 (https://www.httrack.com/)

**Comment by pryrt** [comment]
I just did a quick experiment: telling GitHub to download hugo-extended 0.57.2 instead of 0.82.0 fixed the issue 

I will clean it up to use 0.57.2, and do a new PR to get back to _index.md using

**Comment by donho** [comment]
I cannot reproduce the bug on my PC with `.md` extension.
But OK for only this file, because the right column links disappear when `.md` extension is changed to `.html` one (which is not important for the first page):
![image](https://user-images.githubusercontent.com/90293/113445924-01b86900-93f7-11eb-96ff-33ec42e94127.png)

I will create the tag in a short time. Thank you for your assistance.

**Comment by pryrt** [comment]
@donho,

My PR is actually in the process of doing it's checks.  It should be merged within 5 minutes.  I was able to get it working with .md by using the older hugo version, which matches your setup.

**Comment by donho** [comment]
OK. 
If we have to change the extension, it's not so important, let's do it.
Please let me know when you finish your check/commits.

**Comment by pryrt** [comment]
Done.  Looks good to me.

**Comment by donho** [comment]
@pryrt 
Thank you very much!
Tagged & the site is updated. It works like charms!

So the "bug" was due to the version of Hugo? The newer version makes link not working?

**Comment by pryrt** [comment]
@donho ,

Thanks for making the tag.

> So the "bug" was due to the version of Hugo?

Yes, something changed in the way Hugo handles embedded HTML in a .md source file, apparently.

I'm just glad it's working now.

Enjoy your weekend.
