### ISSUE TITLE
Add "Other Toggles and Settings"

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#200]
Since notepad-plus-plus/notepad-plus-plus#9732 is moving the preference out of **Settings > Preferences > MISC**, it needs to be documented somewhere, per @mere-human's [comment](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9732#issuecomment-821823797).

We can discuss the best place for it in this issue.

**Comment by pryrt** [comment]
I think that we might just want to add a new heading at the end of preferences.md, something like **Other Toggles and Settings**, which could be used for describing this, and other toggles and settings that aren't discussed elsewhere (like **View > Show Symbol > ...**, which are remembered settings, but aren't in any of the preferences dialog pages).

**Comment by mere-human** [comment]
> something like **Other Toggles and Settings**, which could be used for describing this, and other toggles and settings

Right. This makes sense to me.
Probably, this could also include this toggle:
![image](https://user-images.githubusercontent.com/9664141/115158713-39cad780-a098-11eb-8c42-4eb84e7f90a9.png)

**Comment by pryrt** [comment]
I am going to start working on this over this weekend.

Adding notes-to-self / references here:
* Per the edited notepad-plus-plus/notepad-plus-plus#9732 and notepad-plus-plus/notepad-plus-plus@f7e959d, the final label is `Append Extension`
* The `Save Folder as Workspace` [commit](/notepad-plus-plus/notepad-plus-plus/commit/b9f498f0412bc1806ee238627b6099d26e76e9cf)

**Comment by pryrt** [comment]
@sasumner , as I'm documenting the settings/toggles in the **View** menu, I was reminded that Don mentioned "distraction free mode" mode in the Forum (https://community.notepad-plus-plus.org/post/64771), which will be a combo of FullScreen and PostIt, but with extra margins as well.  I searched the closed issues/commits for "distraction" but couldn't find it.  Do you know an issue or commit that references this feature?  Will it be in the View menu next to Full Screen and Post It, or somewhere else?

**Comment by sasumner** [comment]
@pryrt 

I will actually be quite interested myself to read in the manual about this feature -- when I saw the commit (which I now can't find either), I tried some things with the build from it, and I didn't quite "get it".

I do see it here in the UI, though, if that helps you:
![image](https://user-images.githubusercontent.com/30118311/118410441-740aa300-b65d-11eb-90b3-22320fe64ed4.png)

I know that @Ekopalypse is a fan of this mode, maybe he has something to contribute? :-)

**Comment by pryrt** [comment]
I don't know why I couldn't find it last time; a search on "[distraction](https://github.com/notepad-plus-plus/notepad-plus-plus/search?q=distraction&type=commits)"  worked this time.  Looking at the initial commit (notepad-plus-plus/notepad-plus-plus@cbf3d2c), based on where constants are placed, it looks like the toggle for the mode _is_ in the view menu next to Post-It.

**Comment by pryrt** [comment]
While going through, I have noticed that the View menu is _mostly_ a series of toggle commands , so fit in the "Other Toggles and Settings" section; but a few entries, like **View Current File In...** and **Summary**, are _not_ toggles or settings.

So, asking for other people's opinions, for the "View" menu, should I:
1) Document all of the View menu in "Other Toggles and Settings" section, even for the actions that aren't technically toggles
2) Document most of the View menu here, and find some other place to mention the other view menu entries
3) Create a new file to document the complete View menu, and just have "Other Toggles and Settings" have a quick pointer like "many of the entries in the View menu act as toggles for the current instance of Notepad++ or for this and subsequent runs of Notepad++; see the documentation of that menu for details."

**Comment by sasumner** [comment]
I like number 3.

**Comment by mere-human** [comment]
Option 3 looks good.
Though, if it's a lot of work, then having just an option 2 is fine.

> 3\. Create a new file to document the complete View menu, and just have "Other Toggles and Settings" have a quick pointer like "many of the entries in the View menu act as toggles for the current instance of Notepad++ or for this and subsequent runs of Notepad++; see the documentation of that menu for details."

**Comment by Ekopalypse** [comment]
@pyrt - you are right, it is a toggle and sits next to the post-it
![image](https://user-images.githubusercontent.com/47723516/118467145-d7e7a700-b703-11eb-81f8-f9bdc2c33255.png)

The values in the  setting dialog are for the editable part of the scintilla component. (see current line width changes)

Left and Right: the **_higher_** the value the smaller the editable size.
![image](https://user-images.githubusercontent.com/47723516/118468144-c3f07500-b704-11eb-86fa-799c213996ca.png)

![image](https://user-images.githubusercontent.com/47723516/118468238-db2f6280-b704-11eb-8a89-32856d7f83b5.png)

Distraction Free: the **_smaller_** the value, the smaller the editable size

![image](https://user-images.githubusercontent.com/47723516/118468510-2184c180-b705-11eb-9117-0a53f534ecd6.png)

![image](https://user-images.githubusercontent.com/47723516/118468878-7c1e1d80-b705-11eb-95f3-9e879365cdd3.png)

Screenshots were made with min and max values.

**Comment by sasumner** [comment]
Note that @Ekopalypse 's first screenshot shows F12 assigned to `Distraction Free Mode`.
I think that is probably something he assigned, not default behavior.

Side note:  A user may really want to assign a shortcut to this because in my testing of the feature, the `+` in the upper right of the distraction-free-mode screen does NOT always appear.

Reading through the rest of what @Ekopalypse wrote (and thanks for that BTW!), this new feature definitely requires some excellent documentation.

**Comment by Ekopalypse** [comment]
Right, I did, by default no keyboard shortcut was assigned.
On Windows7, I haven't had the issue with the missing + sign. I toggled it, maybe 50 or more times and it was working 100%. Another Windows 10 issue??

**Comment by sasumner** [comment]
> I haven't had the issue with the missing + sign

Maybe it had something to do with being in DFM and having the Prefs window open at the same time and poking and prodding at it?  :-)  I don't know...at this point I haven't noticed a reliable way to repro.
