### ISSUE TITLE
Make npp-usermanual a better site

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/npp-usermanual#21]
The user manual of Notepad++ has been deployed here (generated by Hugo, by using Hugo book theme), it looks and feels much better, and easier for the navigation:
http://u725080053.hostingerapp.com/

It needs a good domain name (blablabla.org). Any idea for the new domain name ?

ps. The navigation on smartphone is awesome too!

**Comment by donho** [comment]
@dail8859  @chcg  @pryrt  @sasumner 
`npp-user-manual.org` is the domain name in my mind currently.
If you don't have any better name, it will be used.

**Comment by donho** [comment]
Or `nppusermanual.org`

**Comment by donho** [comment]
Or `npp-usermaual.org`

**Comment by donho** [comment]
Please vote.

**Comment by sasumner** [comment]
I like `npp-user-manual.org`.  The `-` make it look cleaner.

**Comment by sasumner** [comment]
> Or `npp-usermaual.org`

The spelling is a horror on this one. :)

**Comment by donho** [comment]
"Avoid Hyphens in Your Domain Name"
https://robpowellbizblog.com/choosing-a-domain-name-for-seo/

**Comment by sasumner** [comment]
>Avoid Hyphens

Ah, well...then I vote `nppusermanual.org` so we are back where we started.

**Comment by donho** [comment]
On the same time, npp is an abbreviation so it may bring the confusion. Fuck CEO then.

**Comment by donho** [comment]
``npp-bible.org` ?

**Comment by dail8859** [comment]
I vote for `npp-user-manual.org`

Though if it didn't have to be its own domain my preference would be `notepad-plus-plus.org/manual` but understand due to hosting requirements.

**Comment by pryrt** [comment]
Yeah, I think `npp-user-manual.org` is most clear

**Comment by donho** [comment]
Done.
Domain name has been applied on the site:
http;//npp-user-manual.org/
