### ISSUE TITLE
Change/remove references to "UCS-2"

### ISSUE THREAD

**Issue by sasumner** [notepad-plus-plus/npp-usermanual#212]
I think there was a reworking of the code recently where UCS-2 encoding was replaced with UTF-16.
However, I still see "UCS-2" used in the manual ("Preferences" section).

**Comment by pryrt** [comment]
Reference: notepad-plus-plus/notepad-plus-plus@6834d79

So, I'll note that it's a v7.9.6 update when I make the doc changes.
