### ISSUE TITLE
Documentation Style Guidelines

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#25]
As I've been working on my contributions, I've wondered about a few questions regarding consistent formatting of the help documentation, which need discussion from the team, so we can come to a consensus:

1. For menu entries, how do we want to format / highlight that it's a menu name / entry?
    1. How to format the text
        * Bold? **File > Save**
        * Italic? _File > Save_
        * Code-text? `File > Save`
        * Quoted? "File > Save"
        * Raw?  File > Save
    2. if there's a hyperlink, do we still add extra styling, or leave the hyperlink as the only styling:
        * both: [**Settings > Preferences > MISC.**](https://npp-user-manual.org/docs/preferences/#misc)
        * just link: [Settings > Preferences > MISC.](https://npp-user-manual.org/docs/preferences/#misc)
    3. What separator to use for sub-menus?  
        * Just the greater-than?  File > Save
        * Just the two-character "arrow"?  File -> Save
        * ASCII vertical bar?  File | Save
        * Unicode arrow?  File → Save
        * Unicode triangle? File ▶ Save
    4. For settings entries, or particular attributes of a particular style, should it be formatted like everything else before it, or use a different style
        * For example, in [Settings > Preferences > MISC. documentation](https://npp-user-manual.org/docs/preferences/#misc), I have all the options with tick-boxes formatted in \`backticks\`.  But I don't do similar for the sections I added in #24 

2. For text where we want the reader to understand it as text to type or enter (such as regular expressions), should we use quotes, or use code-formatting (ie, ``` `backticks` ```)
    * Regex: `[a-z]+?`
    * Regex: "[a-z]+?"

3. For file names / paths, should we use quotes, backticks, or something else?
    * talk about `stylers.xml` config file (for example, [here](https://npp-user-manual.org/docs/preferences/#configuration-file-stylers-xml))
    * talk about "stylers.xml" config file

4. How long should a page be before we break it into multiple pages?
    * For example, the [Preferences](https://npp-user-manual.org/docs/preferences/) page is getting really long, with the Preferences, Style Configurator, and Shortcut Mapper

Feel free to edit the issue (or just include it in your comments) if you have more style questions to add...

Once we come to a consensus, we can probably update CONTRIBUTION.md to indicate these style rules.

**Comment by pryrt** [comment]
My votes:
1. Menu / options
    1. I lean toward bold: **File > Save** (which is the style I now use in my forum posts, though I used to use backticks, but I'd be happy with any except raw.
    2. I don't care either way
    3. I tend toward `>`.  I know I've seen `->` elsewhere in the documentation set.  In Microsoft / Windows forums, I often see `|`.  I used to like `▶`, but it's just too hard to enter the character.
    4. asking for feedback
2. I am strongly for backticks / code-formatted, especially for regular expressions
3. I personally like backtick-formatted for file-names as well, but could be convinced otherwise
4. I'd probably vote to split (and would be willing to do the PR for it), but since it was one of the original list-of-single-pages in Don's outline, I didn't want to arbitrarily decide for the group that it should be split.

**Comment by donho** [comment]
Here's my vote (for the subject I follow):

> 1. For menu entries, how do we want to format / highlight that it's a menu name / entry?
>    1. How to format the text

        * Code-text + bold `**File > Save**`

>    2. if there's a hyperlink, do we still add extra styling, or leave the hyperlink as the only styling:
>        * just link: [Settings > Preferences > MISC.](https://npp-user-manual.org/docs/preferences/#misc)
>    3. What separator to use for sub-menus?  

        * Just the two-character "arrow"?  File -> Save


> 2. For text where we want the reader to understand it as text to type or enter (such as regular expressions), should we use quotes, or use code-formatting (ie, ``` `backticks` ```)

 ``` `backticks` ``` is good IMO

> 3. For file names / paths, should we use quotes, backticks, or something else?

why not `*c:\myFolder\myFile.txt*` ?

> 4. How long should a page be before we break it into multiple pages?
    * For example, the [Preferences](https://npp-user-manual.org/docs/preferences/) page is getting really long, with the Preferences, Style Configurator, and Shortcut Mapper

The theme we use "Hugo book" has some bug on subsection unfortunately. OTOH, we have the navigation bar on the right so it's still bearable. But I agree with you, long article should be broken down in long term.

> Once we come to a consensus, we can probably update CONTRIBUTION.md to indicate these style rules.

Good point. I let you guys update it once the decision is taken.

**Comment by sasumner** [comment]
My votes (I did not look at any of the previous voters opinions before answering):

![image](https://user-images.githubusercontent.com/30118311/64453501-af965100-d0b6-11e9-8d35-97b5fcb93066.png)

I guess I don't really understand sect. 1, point iv.

![image](https://user-images.githubusercontent.com/30118311/64453512-b4f39b80-d0b6-11e9-93c4-ebdd29f1287e.png)

Additional for sect. 2, I think this is a MUST!  Having quotes in there, ugh!: users will type/copy the quotes along with the real stuff, surely as I live and breathe!

![image](https://user-images.githubusercontent.com/30118311/64453518-bae97c80-d0b6-11e9-8fd2-ed543fa9e260.png)

Additional for sect. 3, I like the clean look of no quotes, but does this risk overusing the "backtick" highlight style?  I don't think so, but ...?

For sect. 4, need there be a limit?  To continue with the Preferences example, it is broken down nicely on the righthand side when viewing the hugodocs and even if goes beyond one screen it isn't a real problem (so why limit it, with some sort of artificial limit?) 

MY BIGGEST AND MOST-WEIGHTY VOTE:  Peter, please decide and move forward.  I can live with and follow (if doc'd well in CONTRIBUTION.md) whatever you think is best.

**Comment by pryrt** [comment]
For 1.iv, I was talking about 
![Imgur](https://i.imgur.com/qfCX1PY.png)
where `☐ Enable` was an option in the dialog.  In that section, I used backticks, but they are getting rather overused.  I might just make them bold like menu items.

Looks like there's concensus on 2 and 3 (I didn't think there would be much difference of opinion on those, just wanted to make it more democratic); bold is winning on menu items; we're completely split on submenu separator :-).  If there aren't any more comments in the next few days, I'll probably just make an executive decision on the undecided item, and then update CONTRIBUTION.md and work on cleaning up the existing discrepancies.

**Comment by sasumner** [comment]
>1.iv.: ...make them bold like menu items

Very reasonable

>we're completely split on submenu separator 

I certainly don't dislike `>` or `->` or even `|` in any way; I just voted for my favorite.  Really the important thing is just having a decision saying "This is the way we are going..." is better than any individual choice!
