### ISSUE TITLE
Add more details about Remember last used directory preference

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/npp-usermanual#258]
The section about Preferences > Default Directory > Remember last used directory lacks some details.
The last used directory should be remembered only if the file open/save dialog was confirmed.
If file dialog was cancelled, the current directory should be intact.
This was noted by Don HO in [this](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10100#issuecomment-873671758) comment in discussion here https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10100
Also, the behavior described above can be observed in Notepad++ version 7.9.5 and earlier.
So it is worth documenting such details.

**Comment by pryrt** [comment]
@mere-human ,

I never personally use the "remember last directory", so I'm not sure I can describe it to your satisfaction.  
Moreover, when I switch to that mode in a fresh portable copy of v7.9.5, I don't seem to see the behavior I think you described.
* Create new file with text; Save As => 
    * started in portable v7.9.5 directory
    * I manually change to directory `...\FolderForFirstFile` 
    * I set the name `mere.txt` and hit **Save**
* Create new file with different text; Save As => 
    * expected it to start in `...\FolderForFirstFile`, because that's where my last confirmed Save/SaveAs dialog ran from;
    * actually started in portable v7.9.5 directory again
    * manually change to `...\FolderForSecondFile`
    * type name `human.txt` and click **Save**
* Save As on the same `human.txt` with no changes =>
    * expected it to start in `...\FolderForSecondFile`
    * actually started in portable v7.9.5 directory again
    * manually change to `...\FolderForSecondFile`
    * type name `human2.txt` and hit ENTER to save
* Save As on the same `human2.txt` with no changes =>
    * expected it to start in `...\FolderForSecondFile`
    * actually started in portable v7.9.5 directory again
* Close `human2.txt`
* File > Open
    * starts in portable v7.9.5
    * navigate to `...\FolderForSecondFile`
    * click on `human.txt`
    * click on **Open**
* Save As on `human.txt` with no changes =>
    * expected it to start in `...\FolderForSecondFile`
    * actually started in portable v7.9.5 directory again

Gave up.  In v7.9.5, I cannot get "Remember last used directory" to change the directory, no matter what I do.

Fresh unzip of v8.1 portable
* Create new file with text, Save As =>
    * expect to default to v8.1 portable folder
    * it does
    * change directory to `FolderForFirstFile`
    * type `peter.txt` and hit ENTER to save
* Create new file with text, Save As =>
    * expect to start in `FolderForFirstFile` 
    * it does!
    * change directory to `FolderForSecondFile`
    * type `jones.txt` and click **Save** to save
 * Create third new file with text, Save As =>
    * expect to start in `FolderForSecondFIle`
    * this time, it started in v8.1 portable
    * I am so confused
* File > Open:
    * started in portable
    * change to `FolderForFirstFile` and open `mere.txt`
* File > Open:
    * started in `FolderForFirstFile`
    * change to `FolderForSecondFile` and open `human.txt`
* File > Open:
    * started in `FolderForSecondFile` 
    * change to `FolderForFirstFile` and click on `peter.txt`, but **Cancel**
* File > Open
    * started in `FolderForFirstFile` -- so I confirmed the bug for v8.0-and-newer that the open-command is following the last Open chosen, even if it was canceled

So my behavior seems weird to me: in v7.9.5, neither Save As no Open dialogs seemed to influence the last-used directory for Save As or Open.  For v8.1, the Save As _sometimes_ seems to work, but not always; and the Open seems to always change the directory, even if you hit cancel.

-----
```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\usr\local\apps\npp\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```
-----

```
Notepad++ v8.1   (64-bit)
Build time : Jun 17 2021 - 01:56:07
Path : C:\usr\local\apps\npp\npp.8.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
````

**Comment by sasumner** [comment]
More weirdness:  The _Default Directory_ setting seems to affect the _Directory:_ box in _Find in Files_, when one attempts to use _Follow current doc._.  This is unmentioned in the documentation, and it is possibly buggy in the code.

**Comment by mere-human** [comment]
> Create third new file with text, Save As =>
> * expect to start in `FolderForSecondFIle`
> * this time, it started in v8.1 portable
> * I am so confused

I couldn't reproduce it in v8.1.1. Maybe, there were some extra steps that had impact.
Or it could be this bug https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10095



> * File > Open:
>   
>   * started in `FolderForSecondFile`
>   * change to `FolderForFirstFile` and click on `peter.txt`, but **Cancel**
> * File > Open
>   
>   * started in `FolderForFirstFile` -- so I confirmed the bug for v8.0-and-newer that the open-command is following the last Open chosen, even if it was canceled

So this should be fixed in the upcoming version since the bug I mentioned above was fixed.
I can't reproduce it on the current build from Notepad++ master branch.

---

In conclusion, I think it makes sense at least to mention in documentation, that the directory is remembered only if _Open/Save_ button is pressed but not _Cancel_. Because, that was a surprise for me. I didn't know that until Don had mentioned it.

**Comment by mere-human** [comment]
> More weirdness: The _Default Directory_ setting seems to affect the _Directory:_ box in _Find in Files_

Should it not? Was it the same always?

**Comment by sasumner** [comment]
>Should it not?

I don't know. :-)

Notice that my earlier comment mentioned the _Follow current doc._ in the _Find in Files_ tab.
If this checkbox is ticked, it should definitely "follow the current" doc into the _Directory_ box when _Find in Files_ command is executed.
It certainly does this if _Default Directory_ is set to the top radio button (which is also called _Follow current document_).
But when _Default Directory_ is set to a different choice, when _Follow current doc._ is ticked in _Find in Files_, it should DEFINITELY do that, not pay attention to the _Default Directory_ setting.
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8045 for which I will have a PR soon for...

**Comment by mere-human** [comment]
> But when _Default Directory_ is set to a different choice, when _Follow current doc._ is ticked in _Find in Files_, it should DEFINITELY do that, not pay attention to the _Default Directory_ setting.

Ok, this seems like a different problem. And there is even a dedicated issue about that which is good.
But when the _Follow current doc._ is not checked, the current behavior that respects _Default Directory_ seems expected to me.

**Comment by sasumner** [comment]
>this seems like a different problem

Yes, but when these settings affect the _Directory_ box in _Find in Files_, it gets sucked in as well.
It may well belong in a separate issue, but I'd think that the _Directory_ box in _Find in Files_ should only get populated with the "last used directory" if the _Directory_ box is empty.
...and its behavior should be documented (making it topical to THIS issue :-) )
