### ISSUE TITLE
Release usermanual for v8.1.1?

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#259]
@donho, the usermanual should be ready to match the features added in v8.0 - v8.1.1.

Since you've triggered the v8.1.1 auto-updater, did you also want to trigger a new release of the user manual to the website at this point?

Thanks

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/npp-usermanual/commit/4c9211cf0f379b18dfbfc63db42478fe91be1ecc
