### ISSUE TITLE
Deployment Guide?

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#308]
After a [recent conversation](https://community.notepad-plus-plus.org/topic/22449/bak-file-as-new-default/) with someone in the Community Forum who was trying to make configuration changes to propagate while deploying to thousands of machines/users, I have come to the realization that we might be able to add a new page that could work towards being a "deployment guide".  

Unfortunately, I don't have the expertise.

What would be great is if anyone (and if I pointed you here from the Forum, that means _you_) who have experience in the deployment realm (especially if you have _success_ in the Notepad++ deployment process) were willing to lend a hand, by giving some notes, or at least coming up with a list of questions that deployers will likely want answers to, I might be able to start working on such a thing.  Feel free to reply here to start collaborating

At the very least, I'm going to want to further explain in the config-files doc that the `___.model.xml` files are used as the sources for what ends up in `%AppData%\Notepad++\___.xml`, which might at least give the hints as to them being "global configuration" locations.  But a more detailed version could go well in a new file, and I wouldn't know what _should_ go in that.

**Comment by donho** [comment]
It's a good initiation. However, the subject is out of scope for Notepad++ User Manual.
I suggest to post "Deployment Guide" on [FAQ Desk](https://community.notepad-plus-plus.org/category/7/faq) or [Notepad++ Wiki on Github](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki).
