### ISSUE TITLE
Next website release

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#320]
Don,

I believe that I've updated the manual with all the important changes and clarifications for v8.2.1, v8.3, and v8.3.1.

I believe it is ready for the next release to the website.

**Comment by donho** [comment]
I will update Notepad++ User Manual website ASAP.
Thank you Peter for the update!

**Comment by donho** [comment]
@pryrt 
Done.
I add also Path completion (https://github.com/notepad-plus-plus/npp-usermanual/commit/ad2db65e11ba2c894c8b9880535fb01217466cc3). Feel free to modify if need.
