### ISSUE TITLE
"Download offline User Manual" link is broken

### ISSUE THREAD

**Issue by ehharvey** [notepad-plus-plus/npp-usermanual#321]
When accessing the online Notepad++ manual [here](https://npp-user-manual.org/), I am unable to download an offline copy via the 'Download offline User Manual' button.

The download button eventually redirects me to `https://github.com/notepad-plus-plus/npp-usermanual/releases/download/2.9/nppUserManual.zip`, which doesn't exist.

I think this is because the latest release (2.9) lacks an `nppUserManual.zip` asset. This asset is present on previous manual releases (e.g. 2.8). Changing the above mentioned url to `.../download/2.8/nppUserManual.zip` lets me download an offline copy of the previous manual release.

**Comment by pryrt** [comment]
in [a different issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11239#issuecomment-1046133513), @donho commented 
> @pryrt The following url: https://github.com/notepad-plus-plus/npp-usermanual/releases/download/2.9/nppUserManual.zip shows "Not found".
> 
> Should you provide the nppUserManual.zip for the indicated url or we should modify the url?

It looks like the GitHub action aborted in the middle.  I re-ran the action, and now release 2.9 has the asset, and the link works again.
