### ISSUE TITLE
Improve section on "folding"

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#324]
The section describing code folding could be improved.  I'll supply some proposed new content in this area.

**Comment by alankilborn** [comment]
The following posting is an attempt at an improvement on the "Folding" [section](https://npp-user-manual.org/docs/views/#folding) of the manual and is meant as a total replacement for everything beyond the "Folding" header.

This is mainly driving by noticing that the Shift and Ctrl mouse behavior is undocumented, which lead to noticing that the whole Folding section is rather "light".

Moderator, please consider adopting in your own way; changes to this proposal are very welcome and no offense to be caused by changing any part of it.  Also, please validate what I say about the Shift and Ctrl modifiers -- I find this action by the program to be not at all obvious and I'm not 100% sure I captured said behavior correctly and adequately.

**Comment by alankilborn** [comment]
To "fold" text means to temporarily remove from view a block of lines that is hierarchically subordinate to a line directly preceding the block; to "unfold" the text means to reveal that block of text.  Another term for folded is "collapsed" and the corresponding term for unfolded is "uncollapsed".  When text lines are folded/collapsed, a horizontal line is drawn across the editor window to indicate that something is not currently being displayed.

Folding is only possible for file tabs whose language supports it, e.g. Normal Text has no folding rules and thus cannot be folded.  Folding is based on the current syntax highlighter lexer for a programming language or User Defined Language, and the folding follows rules defined in that lexer or UDL.

For language types that support "code folding", an additional margin will be created along the left edge of the editing window; this is called the "fold margin".  A fold margin also appears in the "Search results" panel/window when it is shown; here the hierarchy separates the output from previous search runs into groups.

In the fold margin will appear symbols for expansion and contraction of the code hierarchy, according to folding rules for the current language.  The symbols that can appear in the margin are:

- An icon with a "-" symbol, meaning unfolded and the line it is on is a possible future fold point
- An icon with a "+" symbol, to signify that some amount of lines below the current line are folded
- Bracketing symbology to show the extent of what could be folded when "-" is the symbol on a foldable "header" line

The exact appearance of the symbols is governed by the Fold Margin Style setting in the Margins/Border/Edge section of the Preferences.

If folding blocks are "nested" (contained inside other folding blocks), the outermost block is level 1, the block immediately inside that is level 2, and so on.

There is a group of folding-related commands on the View menu, which will allow the folding or unfolding of line-blocks of text:

- Fold All and Unfold All will collapse or reveal all fold blocks in the current file
- Collapse Current Level and Uncollapse Current Level will collapse or reveal the block based on the line of the editing caret
- The entries in the Collapse Level and Uncollapse Level sub-menus will collapse or reveal every level N block in the active file

Folding/unfolding can be actuated by menu commands on the View menu relating to "fold" or "collapse", or by any shortcut keys assigned.  It can also be invoked by using the mouse and clicking on the symbols in the fold margin.  Clicking on a "-" symbol will collapse the lines at that level and below so they are no longer shown; clicking on a "+" symbol will expand the fold so such lines will again be displayed.

As folding can be nested there is some remembering of internal fold states while the outer states are manipulated.  However, there are some ways to override this behavior:

- Clicking a "-" or "+" fold symbol while holding the Shift key:  Any internal folds in the clicked-upon tree will be uncollapsed, so that the whole sub-tree hierarchy will be shown fully expanded; if the tree is already fully expanded, Shift-clicking the top-level "-" symbol will do nothing
- Clicking a "+" fold symbol while holding the Ctrl key:  Same as clicking a "+" fold symbol while holding the Shift key
- Clicking a "-" fold symbol while holding the Ctrl key:  Collapses at the line of the click point, and collapses all subordinate/internal fold points as well (although this won't be revealed to the user until the fold just created is expanded)

The current fold state of lines is not remembered from one Notepad++ run to the next, nor is it saved in the automatic or a manually-saved session file.  It is intended to be very temporary.  When a file is reloaded by any means it always loads with all lines showing (no "+" will be visible anywhere in the file's fold margin).

**Comment by pryrt** [comment]
I have a branch with a slightly-modified version of your [Folding](https://github.com/pryrt/npp-usermanual/blob/foldingUpdate/content/docs/views.md#folding) section.  Does that look good to you?

**Comment by alankilborn** [comment]
>Does that look good to you?

Looks great -- I think this section is a whole lot better now.  :-)

**Comment by alankilborn** [comment]
@pryrt Is it best to add a note in the manual that the Shift and Ctrl modifiers with the mouse DON'T work the same way in the _Search results_ window as in the editing windows, or put in an issue (against N++) requesting that they be made to work the same?  They are not supported in the _Search results_ window.

**Comment by pryrt** [comment]
In v8.2.1, with the "outer" layer being the search header line and the inner layers being each file's results, I seem to get the same behavior in the Search Results as in the main editor

**Comment by alankilborn** [comment]
You're right, I must have misjudged it when I tested it; sorry for the noise.
