### ISSUE TITLE
Command line parameter openFolderAsWorkspace

### ISSUE THREAD

**Issue by xylographe** [notepad-plus-plus/npp-usermanual#35]
The command line parameter `-openFolderAsWorkspace` appears to be missing in [command-prompt.md](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/command-prompt.md).

**Comment by pryrt** [comment]
@xylographe , does this cover it?

**Comment by xylographe** [comment]
Yes, it does! Thank you.
