### ISSUE TITLE
switch from -z to -pluginMessage

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#353]
per https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11589#issuecomment-1114717179
will need a note that says the version number (v8.5, or v8.4.1, whichever is next / includes the change)

**Comment by pryrt** [comment]
@donho , you mentioned you want `-z` "undocumented".  

But if `-z` is still the [officially-recommended way](https://npp-user-manual.org/docs/other-resources/#notepad-replacement) for handling "Notepad replacement", then I would maintain that `-z` should still stay in the [command prompt](https://npp-user-manual.org/docs/command-prompt/) section.  

I would prefer to just phrase it so that the documentation for `-z` says something like "this is used for the [Notepad replacement](https://npp-user-manual.org/docs/other-resources/#notepad-replacement) , but should not be used for any other reason".

For documenting the new command-line-argument, I would say something like "`-pluginMessage="message in quotes"`: if plugin developers need extra command line arguments, then users can add this option, and the plugin will be [notified](# "link to new NPPN_CMDLINEPLUGINMSG") that it can parse that string for extra information, where the link would cross-reference the new NPPN_CMDLINEPLUGINMSG notification.

**Comment by donho** [comment]
@pryrt 
> But if -z is still the [officially-recommended way](https://npp-user-manual.org/docs/other-resources/#notepad-replacement) for handling "Notepad replacement", then I would argue that -z should still stay in the [command prompt](https://npp-user-manual.org/docs/command-prompt/) section. I would prefer to just phrase it so that the documentation for -z says something like "this is used for the [Notepad replacement](https://npp-user-manual.org/docs/other-resources/#notepad-replacement) , but should not be used for any other reason".

OK, I think it's reasonable.

> For documenting the new command-line-argument, I would say something like

>>    -pluginMessage="message in quotes": if plugin developers need extra command line arguments, then users can add this option, and the plugin will be [notified](https://github.com/notepad-plus-plus/npp-usermanual/issues/353#) that it can parse that string for extra information

> ... where the link would cross-reference the new NPPN_CMDLINEPLUGINMSG notification.

No, please don't. 
It's like incest: the fact that I can have sex with my sister doesn't meant that I should do it.
Our goal is provide a simplified and unique way for passing command line arguments to plugins. So we don't provide other ways officially to them.

OTOH, the Notepad replacement doesn't work on my Windows 11 - if it doesn't work anymore, `-z` support will be removed in the future. So let's make the isolation for each feature then we won't have the trouble in the future.

**Comment by donho** [comment]
Oups, sorry, I misread it.
Yes, please just talk about -pluginMessage="message in quotes" but don't mention `-z` anymore for the plugin usage.
