### ISSUE TITLE
Keyboard can now be used to change tabs in Find dialog

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#375]
User manual is out-of-date here:

![image](https://user-images.githubusercontent.com/77065706/175655521-9c1c9139-ff19-4ff7-ad15-f5926db192c8.png)

https://npp-user-manual.org/docs/searching/#:~:text=once%20this%20input%20focus%20is%20achieved%2C%20there%20is%20no%20possibility%20to%20switch%20to%20another%20of%20the%20tabs%20via%20the%20keyboard

It **_IS_** possible to switch tabs via keyboard, by invoking the shortcut keys for the different tabs while one of the tabs has input focus, e.g. if the _Find_ tab has focus and Ctrl+h is pressed, system will switch to _Replace_ tab.

Capability was added in 8.1.3; see point [6](https://community.notepad-plus-plus.org/topic/21651/notepad-v8-1-3-released).

Also, note nearby revised text for the above that a Ctrl+f press while input focus is on the Find tab will reposition the Find window; user confusion exists: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/905#issuecomment-1165860229

**Comment by pryrt** [comment]
and the `Ctrl+F` repositioning was re-enabled in v8.3.3: see point [4](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes#833)

**Comment by pryrt** [comment]
@alankilborn , how does this sound?

> *Note:*  Prior to v8.1.3, doing any of those keystrokes (`Ctrl+F`, `Ctrl+H`, `Ctrl+Shift+F`, or `Ctrl+M`) once would open the Find dialog or bring it into focus; from the main dialog, hitting `Ctrl+F` would re-center the dialog (no matter which tab of the dialog you were on); but you could not use the shortcuts for the other versions to switch between the tabs.  In v8.1.3 through v8.3.2, once the dialog was active and in focus, hitting the keystrokes would switch between the tabs on that dialog; however, these versions would _not_ re-center the dialog if you hit `Ctrl+F` again.  Starting in v8.3.3, the first hit of one of those shortcuts would bring up the dialog or bring it into focus; from there, hitting one of the _other_ shortcuts would change tabs in the dialog (as with v8.1.3), but hitting the shortcut for the tab you are already on will re-center the dialog (so `Ctrl+F, Ctrl+F` will center the Find dialog, `Ctrl+H, Ctrl+H` will re-center the Replace dialog, and so on).

**Comment by alankilborn** [comment]
It sounds really good, but maybe too good.  You know I'm not a big fan of carrying along all the history... but there's more than me in the universe.
