### ISSUE TITLE
Missing backtick

### ISSUE THREAD

**Issue by xylographe** [notepad-plus-plus/npp-usermanual#38]
At the end of [CONTRIBUTION.md](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/CONTRIBUTION.md) (end of section **Cross-Links**) the last sentence should end with a closing backtick and a full stop.
```
the syntax `[**Preferences > Style Configurator**](../preferences/#style-configurator)`.
```

**Comment by pryrt** [comment]
fixed

**Comment by xylographe** [comment]
Thank you, @pryrt.
