### ISSUE TITLE
Ada plugin template URL should point to "newer" (ca. 2019) version

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/npp-usermanual#382]
The current link to the [Ada plugin template][0] goes to a 404 page. I needed the [Wayback Machine][1] to find it. The documentation disclosed the developers' website, where they're hosting a much better 2.0 version, "updated to work with 64-bit Notepad++ v7.7.1", to quote from the new version's README: http://white-elephant.ch/notepad.php

The template code is practically free of dangerous Scintilla APIs. It makes one call to [`SCI_GETLENGTH`][2] that assumes an unsigned 32-bit number of bytes (given the constraints of the `Natural` integer subtype <sup>1</sup>), but it's an isolated case, and safe for everything smaller than multi-GiB files. The latest N++ version can run it with only one minor quirk: the docking panel's `X` button doesn't seem to work.

![hello-ada-2 0-npp-8 4 3](https://user-images.githubusercontent.com/59004801/178131898-27b2c65f-67e0-477a-97df-325f179e3ea2.png)

---
<sup>1.</sup>
~~~ada
function Buffer_Content (Handle : Object) return String is
  The_Content : aliased String(1 .. Natural(Execution_Of(Handle, SCI_GETLENGTH)) + 1);
begin
  Execute(Handle, SCI_GETTEXT, The_Content'length, Convert(The_Content'address));
  return The_Content;
end Buffer_Content;
~~~

[0]: https://npp-user-manual.org/docs/plugins/#in-other-languages
[1]: https://web.archive.org/web/20190423151117/https://notepad-plus-plus.org/assets/files/NppHelloAdaDemo.zip
[2]: https://www.scintilla.org/ScintillaDoc.html#SCI_GETLENGTH

**Comment by pryrt** [comment]
fixed by fb816cb
