### ISSUE TITLE
Purge search results: circular reference

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#386]
per [NPP Issue#12000](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12000#issuecomment-1208245543),
> More from the user manual, [HERE](https://npp-user-manual.org/docs/searching/#search-results-window:~:text=menu%20item%20entitled-,Purge%20for%20every%20search,-is%20present%20in) is some info about purging old results. Hmm, it is rather a circular reference: "Purge for every search...running a search will purge old results." @pryrt Could that be elaborated on a bit more to remove the circle?

**Comment by pryrt** [comment]
@alankilborn, 

Currently, the full paragraph reads (emphasis added)
> To some users these older results accumulating are an annoyance – their data may become out of date quickly with changes to files – so Notepad++ 7.9.6 and higher support **a setting that, after turned on, removes any old search data from the window before populating it with new.** The setting is set/cleared by right-clicking anywhere in the Search results window, causing the context menu to appear; a checkable menu item entitled Purge for every search is present in this menu. After turning the feature on, which will cause its menu item to have a checkmark, running a search will purge old results.

... so it already explains that the option "removes any old search data from the window before populating it from the new".  

Would it be sufficient to change from
> The setting is set/cleared by right-clicking anywhere in the Search results window, causing the context menu to appear; a checkable menu item entitled Purge for every search is present in this menu. After turning the feature on, which will cause its menu item to have a checkmark, running a search will purge old results.

to

> To set or clear this setting, right-clicking anywhere in the Search results window, and click on the **Purge for every search** entry: there will be a checkmark to indicate it's on, and no checkmark to indicate it's off.  

... and rely on people having read the previous sentences?

And maybe add:
> _Note_: clicking this option doesn't immediately purge the old results; instead, searches made subsequent to enabling this option will purge the old results.

**Comment by alankilborn** [comment]
Actually, it _was_ okay as written.  But now that you've invested the time, who could argue with the new version -- not me.  :-)
