### ISSUE TITLE
Ready for website release

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#437]
The repo version of the User Manual has been updated to include the Notepad++ v8.4.6 - v8.4.7 features and updates.  Could you release it to the website, now that v8.4.7 has been triggered for auto-update?

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/npp-usermanual/commit/6a641f91a2c7e9c88ff4a3b3914055d183859538
Updated on the website.
Thank you @pryrt !
