### ISSUE TITLE
Clarify "In Selection" doc

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#44]
per [Community forum](https://community.notepad-plus-plus.org/post/48041), there is some ambiguity in the phrasing of the "In Selection".  

* On the **Find** tab, it technically only applies to the **Count**, not the **Find Next** button (it shows this by being in a group-box in the dialog)
* On the **Replace** tab, it only applies to the **Replace All**, not the **Find Next** or **Replace** buttons (it shows this by being in a group-box in the dialog)
* On the **Mark** tab, it's not in a group-box; however, while **Mark All** obeys the checkbox, and **Clear All Marks** both clears marks in the whole document, not just in the selection.

I'd probably phrase it something like 
```
(The **In selection** checkbox applies only to the **Count** in **Find**, only to the **Replace All** in **Replace**, and only to the **Mark All** in **Mark**)
```

**Comment by pryrt** [comment]
or just change from 
```
If you have a region of text selected, and In selection is enabled, it will only search-and-replace / count / mark within that selection of text, rather than in the whole document
```
to
```
If you have a region of text selected, and In selection is enabled, it will only **Count**,  **Replace All**, or **Mark All** within that selection of text, rather than in the whole document.  (The checkbox does not affect other buttons, like **Find Next**.)
```

**Comment by sasumner** [comment]
Since I recently made the "bookmark" checkbox required to be checked in order to clear bookmarks when the "clear all" button is pressed...it sure seems like "in selection" is begging for the same treatment.  Sigh.

**Comment by sasumner** [comment]
Assigned to me because I sort of assumed "ownership" (or maybe "squatter's rights) on the Searching doc?

**Comment by pryrt** [comment]
I didn't even see that you had replied before I made my PR.
I assigned both of us to it, so whoever found the time first would be able to do it.  I found the time sooner than I thought I would.
