### ISSUE TITLE
MRU and tab closing

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#449]
Some info needs to be added concerning behavior when tabs are closed.
Specifically, which tab becomes the new active tab.
Reference discussion here: 
https://community.notepad-plus-plus.org/topic/23893

**Comment by pryrt** [comment]
Would it go better with the other tab-navigation stuff in the cheat sheet?  Or in the MISC>DocSwitcher preferences?

In the preferences section, I was thinking of two short sub-bullet-points
> - When checkmarked: Ctrl+TAB will take you to the most recently used document.  Also, if you close the active tab, it will activate the most recently used tab 
> - When not checkmarked: Ctrl+TAB will take you to the next tab in the Ctrl+TAB menu.  Also, if you close the active tab, it will activate the previous tab in the Ctrl+TAB menu

I am leaning towards in the preferences, but let me know what you think.

**Comment by alankilborn** [comment]
Yes, I was thinking the _Preferences_ approach as well.
