### ISSUE TITLE
webserver not responding

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#452]
@donho,

the webserver for npp-user-manual.org is not responding, since at least 2022-Dec-16 12:50pm GMT (based on timestamps in this forum post https://community.notepad-plus-plus.org/topic/23898/can-t-visit-online-manual-website).  My tests (from laptop, from phone, and using https://isitdownorjust.me/npp-user-manual-org/) confirm that as of 17:56 GMT, it's still down.

**Comment by donho** [comment]
Hi Peter, 
Thank you for your heads up.
I just restart the VM from the hoster, it work again now.
I have no idea though what is the problem.
