### ISSUE TITLE
User manual typing errors

### ISSUE THREAD

**Issue by datatraveller1** [notepad-plus-plus/npp-usermanual#457]
I have read the first four chapters of the user manual and found a few typing errors you might want to correct:

https://npp-user-manual.org/docs/user-defined-language-system/
“using **a existing** plugin”
_correction_: **an existing**

“**langauge**”
_correction_: **language**

“**keywwords**”
_correction_: **keywords**

https://npp-user-manual.org/docs/editing/
“**Using** Alt + Mouse dragging or Alt + Shift + Arrow keys to make a selection in column mode”
_correction_: **Use** would be better

“Note: that the numerical boxes …”
_correction_: **No colon**

“**sopme** call it”
_correction_: **some**

"Revert to **mopdified**"
_correction_: **modified**

**Comment by datatraveller1** [comment]
Hi @pryrt
Thank you very much for the fixes!
Do you know when they will be visible at https://npp-user-manual.org/?

**Comment by pryrt** [comment]
There's normally a new version released to the website every couple of months.

**Comment by datatraveller1** [comment]
Thank you. So actually it is better to read https://github.com/notepad-plus-plus/npp-usermanual instead of https://npp-user-manual.org/ if I want to see the latest version, isn't it?
