### ISSUE TITLE
Test Plugin Locally - Dead Links on Documentation Page 

### ISSUE THREAD

**Issue by viper3400** [notepad-plus-plus/npp-usermanual#46]
Tried to test updated version of NppRexExtractorPlugin as described here: https://npp-user-manual.org/docs/plugins/#test-your-plugins-locally

But links to the tools located at https://notepad-plus-plus.org/pluginListTestTools are dead. Where I can download the tools?

See https://github.com/notepad-plus-plus/nppPluginList/issues/142

**Comment by pryrt** [comment]
@donho, it appears that  https://notepad-plus-plus.org/pluginListTestTools is no longer a valid URL.  Where are the debug executable files that were in that directory now stored?  (I can fix the docs to match the new location, but I don't know where they are.)

Or if they should be there, but aren't, could you fix the website so they are there again?
