### ISSUE TITLE
Consider informing users that manually installed plugins may be blocked for security

### ISSUE THREAD

**Issue by rdipardo** [notepad-plus-plus/npp-usermanual#463]
On the topic of [installing plugins manually], the published docs currently state:

> Once you installed the plugin, you can use (and you may configure) it via the menu “Plugins”.

This description unfortunately elides a potential problem that users are likely to encounter at this step. Executable files from the internet are inherently dangerous, and the default security posture of a PC running any recent version of Windows is to block them.

A plugin DLL or archive downloaded by a web browser will be silently tagged with a ["Mark of the Web" (MOTW)][0]. If it's an archive, the inflated contents [will inherit the MOTW][1] when unzipped by the system's default "Extract all" context menu option. In practise, this means alternate data streams are created for each untrusted file; passing the `/R` flag to the `DIR` command will reveal them.

The presence of an alternate data stream tells the OS not to execute the associated binary. The user is *not* prompted to intervene unless the file in question is an `*.EXE`, in which case a warning dialog appears.

![dont-run-dlg](https://user-images.githubusercontent.com/59004801/210157665-dcee2950-2558-466f-a1a0-2d0bec5b5458.png)

Office documents will likewise open with the "Protected Mode" banner displayed.

![vba-security-risk-banner](https://learn.microsoft.com/en-us/deployoffice/images/security/vba-security-risk-banner.png)

But DLLs will just silently fail to load, usually causing an exception somewhere down the call stack, which users are prone to misdiagnose as a bug, e.g.:

- https://github.com/mohzy83/NppMarkdownPanel/issues/57#issuecomment-1354798788
- https://github.com/oleg-shilo/cs-script.npp/issues/64#issuecomment-1046114822

I would not recommend trying to explain the pitfalls of browser-mediated plugin downloads in as much detail as above. All that's needed is a simple reminder that:

1. Your PC instinctively mistrusts DLLs from the internet, for very good reasons

2. Before attempting to use *any* plugin you downloaded yourself, right-click the DLL and visit the *Properties* context menu. If the *Unblock* option is shown, click the checkbox and click *Apply*, then *OK*.

  ![npp-plugin-MOTW](https://i.ibb.co/C77Wmfx/NPPFSIPlugin-MOTW.png)

[installing plugins manually]: https://npp-user-manual.org/docs/plugins/#install-plugin-manually
[0]: https://nolongerset.com/mark-of-the-web-details/#can-you-explain-more-about-the-mark-of-the-web
[1]: https://github.com/nmantani/archiver-MOTW-support-comparison#comparison-table-of-motw-propagation-behavior-as-of-21-november-2022

**Comment by alankilborn** [comment]
>But DLLs will just silently fail to load

Surely Notepad++ code could be changed to detect the mark-of-the-web on a plugin DLL, and inform the user that this is the reason the DLL could not be loaded?
