### ISSUE TITLE
npp-user-manual.org certificate error

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#515]
@donho,

The past couple of days, I've been getting certificate errors when I go to npp-user-manual.org.

![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/af858082-0522-44d1-99c9-68e074e3a2ca)

![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/ac0b8715-f6b8-4c1b-954d-c360ab226c03)

Today, I downloaded the certificate and looked at it with Windows certificate viewer: it shows it expired on May 7.  You might want to check the domain setup for npp-user-manual.org to make sure it's set to auto-renew its certificate.

![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/c6513171-3823-4fe0-8325-86bc2d58230e)

**Comment by pryrt** [comment]
After [this post](https://community.notepad-plus-plus.org/post/86301), I reloaded the website a few times.  For some of the loads it came up with the expired certificate, and other loads came up with a valid certificate (which doesn't expire until July)

![image](https://github.com/notepad-plus-plus/npp-usermanual/assets/17455758/aa62ebb1-172e-4e05-a26f-341ba312ab1c)

- Expired: Thumbprint = a936548c755915fe750e8f6eba4eab6087aa77ae
- Valid: Thumbprint = 8240da58c09fa3ef6f6443ea3ca81695f5286078

Getting two different certificates from the same site tells me that your host for the website uses a loadbalancing system with multiple machines responding to the same URL.  Normally when a host does that, they take their configuration (including the certificates) from a shared area, but apparently your host has two separate certificate locations, and the certificate on one machine is expired while the other machine has a valid certificate.  They either need to use the same certificate on all their load-balancing machines, or they need to set up each machine to auto-renew the certificates every 3 months when they expire.

**Comment by donho** [comment]
@pryrt 
Thank you for the very detailed analysis and information.
Could you suggest me about the question/demand to my host, in order to solve this problem?

**Comment by pryrt** [comment]
@donho, I would just say something like,

> Hello HOST,
> When people go to npp-user-manual.org, they are sometimes getting an HTTPS certificate with thumbprint 8240da58c09fa3ef6f6443ea3ca81695f5286078 which expires this July, and somes get an HTTPS certificate with thumbprint a936548c755915fe750e8f6eba4eab6087aa77ae which expired on May 7 -- and when they get the expired certificate, their browsers don't show them the website.  
> It appears that you have multiple machines for load balancing (or similar configuration), but that they are using different certificates.  Please either configure them to both use the same certificate; or, if that doesn't work, make sure that both machines are set up to properly renew the HTTPS certificate, so that neither machine is serving an expired certificate.

You can grab my screenshots above to include in the request, as well.

**Comment by donho** [comment]
@pryrt 
Sorry for the late reply. I was traveling, I'm just back home.
After restarting the VPS via the host, the certificate issue seems fixed.
Could you confirm it please?

**Comment by pryrt** [comment]
Yes, now all I get with multiple reloads is a valid cert that doesn't expire until July.  I will close this as fixed.
