### ISSUE TITLE
UDL Docs: Incorporate Ivan's information

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#521]
per https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13737 , we're going to incorporate the info from [Ivan Radić's UDL2 docs](https://ivan-radic.github.io/udl-documentation/) into the User Manual

**Comment by donho** [comment]
@pryrt 
It's been done, hasn't it?

**Comment by pryrt** [comment]
Actually, I never got back to this.

**Comment by donho** [comment]
OK, no problem.
Do it or not, you decide.
