### ISSUE TITLE
Localization directory only in install_directory?

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#524]
per [forum discussion](https://community.notepad-plus-plus.org/topic/13762/disable-menu-activation-for-a-shortcut/15), the it appears that `localization\` directory currently only works as `<install_directory>\localization\` -- the manual currently says it works from either that or AppData.  If we get official clarification on the intention and there's a decision to not change N++ itself, then the documentation will need to be updated to match.

**Comment by alankilborn** [comment]
Reference: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13932

**Comment by pryrt** [comment]
Since I'm editing the Localization anyway (#523), I am going to remove the AppData reference (at least for now).  As such, it will match the current behavior of Notepad++.  If the developers agree that it's a bug and fix it, I will put it back into the manual.

**Comment by donho** [comment]
Localization directory should only be one place: beside of Notepad++ binary.
The current behaviour will be remained.
