### ISSUE TITLE
Reorder and Rename Pages

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#530]
The page order in the User Manual is highly unintuitive.  And some of the page names makes it hard for a newbie (or even an experienced user) to know where to find the information they are looking for.

As some of the other issues have been addressed recently, I've been renaming per those requests; after renaming a couple, I was reminded of how many of the other pages have names that I don't like, so I'd like to update the rest.

This can be accomplished without changing any URLs by just editing their metadata, so links from external sites and internal cross-references will still work, despite being reordered and renamed.

**Comment by victorel-petrovich** [comment]
I'll be happy to give feedback if you'll need.
