### ISSUE TITLE
GettingStarted: Clarify differences between installation methods

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#532]
per  @victorel-petrovich and @mkupper in [Community Forum](https://community.notepad-plus-plus.org/post/88181)

**Comment by victorel-petrovich** [comment]
Hmm, could you reopen this? I've just finished preparing a list of further improments to the Installer-vs-Portable section. 
Here they are:
#### ommisions from original [nice bullted list](https://community.notepad-plus-plus.org/topic/21449/installer-vs-zip-in-windows-10/8?_=1690577871105)
- For Installer
  - the 2.2, could go before "When you use the installer to install to a directory other than "Program Files" ..."
  - the 2.4 , could go before "The installer should also install the [Shell Extension](../shell-extension/) to add **Edit with Notepad++** to the Windows Right-Click context menu."
- For Portable: 
  - the 3.1 (this could be put in the same paragraph as "In a portable edition, the [configuration files](../config-files/#configuration-files-location) will be stored in the same directory where you put `notepad++.exe`. ")

#### other suggested changes :
- In the Installer section:
  - I'd move this to the end, as it's more advanced/needed by fewer users: "If you are doing managed installation or otherwise want to control the installer from the command line, the installer has a few [command line options](../command-prompt/#installer-options)."			
- The "## Install Notepad++ from 7z or zip"  section: 
  - I think it would be clearer to split it into 2subsections, "## Portable" and "## Mini-Portable" (this way will perfectly match the 3 download options)
    - The mini-portable subsection can start with something like "It is basically a more stripped down edition of portable" then list what it lacks compared to the Portable version 
    - Then of course move the last part into the Portable subsection:  "The full portable includes all the themes that ship with the Notepad++ installer, and has all localization files included, and includes the default plugins with the Plugins Admin tool."
 - In Portable subsection: inside the paragraph: "The portable editions do not automatically install Right-Click ...": 
   - Need to replace "Edit with" with "Open with" (that's how it's called in windows standard menues whereever I've seen it) 
   - I think you need to cut out this part "unless you use Windows' **Open  with** feature to permanently associate that type of file with your portable Notepad++" and put it in a separate sentence, because it's a feature built-in in Windows, works regardless of whehther or not one creates the custom "Edit with Notepad++" (via shell extension or registry edits)
 - Also in Portable subsection: add a sentence that to uninstall, you simply delete the unzipped folder.

**Comment by victorel-petrovich** [comment]
I could make a PR myself and then you can review, if you prefer.

**Comment by pryrt** [comment]
Please remember that "Getting Started" is just the essentials for getting started.  It makes sense to do a brief discussion of the differences between installer/portable to be able to make an informed decision as to which package to download, but you don't necessarily need deep detail .

>   * the 2.2, could go before "When you use the installer to install to a directory other than "Program Files" ..."

There's already a whole section about "config files location"

>   * the 2.4 , could go before "The installer should also install the [Shell Extension](../shell-extension/) to add **Edit with Notepad++** to the Windows Right-Click context menu."

Is showing up in the Windows add/remove programs dialog _really_ that critical a piece of information?  That's more of a Windows feature -- if you use an installer, Windows knows how to uninstall it -- and nothing specific to Notepad++.  We're here to document Notepad++, not the OS.

>   * the 3.1 (this could be put in the same paragraph as "In a portable edition, the [configuration files](../config-files/#configuration-files-location) will be stored in the same directory where you put `notepad++.exe`. ")

The **Plugins > Install Plugins Manually** section already explains where plugins go in an installed-vs-portable, so no reason to duplicate it here.  Especially because plugins _always_ go in the same spot relative to the notepad++ executable.

>   * I'd move this to the end, as it's more advanced/needed by fewer users: "If you are doing managed installation or otherwise want to control the installer from the command line, the installer has a few [command line options](../command-prompt/#installer-options)."

I guess it could go at the end of that section rather than the beginning.  I'll work on that.

>   * I think it would be clearer to split it into 2 sections, "## Portable" and "## Mini-Portable". This way will perfectly match the 3 main download options , and also:

There's no difference in the way to install it.  The only difference is how full the directory will be.  I don't see the "perfect match", because in my mind, "mini-portable" is just one of the portable editions.  It's essentially the same product as the full portable, with just less "extra stuff" shipping with it.

But I'll see if i can work on making that one section more coherent.

>   * Need to replace "Edit with" with "Open with" (that's how it's called in windows standard menues whereever I've seen it)

I'll fix that

>   * I think you need to cut out this part "unless you use Windows' **Open  with** feature to permanently associate that type of file with your portable Notepad++" and put it in a separate sentence, because it's a feature built-in in Windows, works regardless of whehther or not one creates the custom "Edit with Notepad++" (via shell extension or registry edits)

Actually, I'll just cut out both the Open With and the Settings > File Associations -- the first is a Windows feature, and the second is already described in the Settings page

> * Also in Portable section: add a sentence that to uninstall, you simply delete the unzipped folder.

Do you really think users need to be told that if they want to uninstall something they installed by unzipping that they have to delete it?

**Comment by pryrt** [comment]
> * Need to replace "Edit with" with "Open with" (that's how it's called in windows standard menues whereever I've seen it)

According to the source code for the Shell Extension (https://github.com/notepad-plus-plus/nppShell), the text is "Edit with Notepad++" -- see [here](https://github.com/notepad-plus-plus/nppShell/blob/71f49c1b34e33d52aa5d5d8180b0ec95865a0e35/NppShell.rc#L393).  That's what's in my v8.5.4 installation.  And when I search both the nppShell and the notepad-plus-plus source code, I cannot find any string that contains "Open With".

Maybe it said "Open with" in _older_ versions, but the current phrase is "Edit With", and as a result, that's what is staying in the User Manual.

**Comment by pryrt** [comment]
#535 includes my updates based on your further inputs.  I think this covers the essentials for a "Getting Started", with sufficient information to make an informed decision as to which edition to download, without repeating information that is already contained elsewhere (the Plugins page already describes installing/updating plugins requiring admin privileges, and the config files contains the _details_ about config file location while this page only does brief mentions with links).

**Comment by victorel-petrovich** [comment]
WRT 2.2 (with installer, user config files go in AppData;) and 3.1 (with Portable, plugins will go in the unzipped folder )
>  don't need to repeat things that are elsewhere in the Manual.

It's up to you, but with such reasoning, you could remove other differences you already included in that section; like, where Config files in case of Portable edition. I think the point was to allow user to quickly get the main the differences, without having to read other detailed pages.

> Is showing up in the Windows add/remove programs dialog really that critical a piece of information? 
> ...
> Do you really think users need to be told that if they want to uninstall something they installed by unzipping that they have to delete it?

No, I think you're right on those. 

> According to the source code for the Shell Extension (https://github.com/notepad-plus-plus/nppShell), the text is "Edit with Notepad++" [...]

I wasn't refering to N++'s shell extension feature, but to Window's built in feature, which is called "Open with... " .
See, in manual you wrote: 

> The portable editions do not automatically install Right-Click context menu, so you will not see Edit with Notepad++ on files unless you use Windows' Edit with feature to permanently associate that type of file with your portable Notepad++

So, again, that Windows' feature to permanently associate that type of file with your portable Notepad++, is called "Open with" not "Edit with".  That's what sees when one right-clicks on any file in Windows. [Google images](https://www.google.com/search?rlz=1C1JJTC_en&sxsrf=AB5stBhrIoLN0TCLvbrIfLhDcfdUTP6Kxw:1690656285186&q=windows+%22Open+with%22+at+right-click&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiT78K6ybSAAxULAjQIHduCAQ8Q0pQJegQIChAB&biw=1707&bih=880&dpr=1.13)

**Comment by pryrt** [comment]
> > don't need to repeat things that are elsewhere in the Manual.
> It's up to you, but with such reasoning, you could remove other differences you already included in that section; like, where Config files in case of Portable edition. I think the point was to allow user to quickly get the main the differences, without having to read other detailed pages.

I think the version in #535 _does_ list the main differences.

> > Do you really think users need to be told that if they want to uninstall something they installed by unzipping that they have to delete it?
> No, I think you're right on those.

Oddly, I ended up including the note on uninstalling, for balance.

> I wasn't refering to N++'s shell extension feature, but to Window's built in feature, which is called "Open with... " . See, in manual you wrote:

No longer relevant.  I don't mention Window's built-in Open With feature anywhere in Getting Started now (#535).

> > The portable editions do not automatically install Right-Click context menu, so you will not see Edit with Notepad++ on files unless you use Windows' **Edit with** feature to permanently associate that type of file with your portable Notepad++
> 
> So, again, that Windows' feature to permanently associate that type of file with your portable Notepad++, is called "Open with" 

So again, that sentence no longer exists in #535.

**Comment by victorel-petrovich** [comment]
Yep, balance is critical :D  .

Well, someone's editings will never be *perfect* by me or any other particular editor, but I guess that's how open collaboration works. Progress is real, perfection is not.
