### ISSUE TITLE
Ready for next Release

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#546]
@donho, 

Since Notepad++ v8.5.6 was just triggered for auto-update, it's a good time for the next User Manual release as well.

It has all the features from v8.5.4, v8.5.5, and v8.5.6 documented, along with many other improvements.

**Comment by pryrt** [comment]
closed by https://github.com/notepad-plus-plus/npp-usermanual/commit/c785712b2dc957bccb39ae32881497c217ccfb54

**Comment by donho** [comment]
Just updated.
BTW, shouldn't it be  `(currently up to v8.5.6)` instead of `(currently up to v8.5.5)` ?

**Comment by pryrt** [comment]
You're right, it should have been updated.  I'll have to get into the habit of updating that before a tag is triggered.
