### ISSUE TITLE
v8.6 - Describe Edit > Multi-Select All/Next menus

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#602]
#598 didn't include the new **Edit** menu **Multi-Select** entries

![](https://community.notepad-plus-plus.org/assets/uploads/files/1700839964905-752d2ed5-42cf-4719-bf3f-9e9738fbdb32-image.png)

**Comment by pryrt** [comment]
@alankilborn, could you take a look and let me know if you think that's reasonable (especially where I just said "analogous to the previous menu" rather than re-describing all those sub-conditions)?

**Comment by alankilborn** [comment]
It definitely seems good as is to me.
