### ISSUE TITLE
new central repo for example UDL language definitions

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#61]
It's been talked about multiple times in the forums, but [this recent post](https://community.notepad-plus-plus.org/topic/18572/where-do-i-find-the-udl-i-m-looking-for) was enough for me to create an issue about it.

Multiple users (myself included) would like there to be a central "official" list of example UDL definition files, like used to be at [NppWiki++ > User Defined Language Files](http://web.archive.org/web/20180814202307/http://docs.notepad-plus-plus.org/index.php/User_Defined_Language_Files) (as archived at web.archive.org).

If we want it to be central/official, the two best ideas that I've seen are 

1) The idea expressed in [that post](https://community.notepad-plus-plus.org/topic/18572/where-do-i-find-the-udl-i-m-looking-for), which is creating a new repo like "https://github.com/notepad-plus-plus/nppUDLList".  To expand on the idea, it could be run by the notepad-user-manual-admin group, but just not be published anywhere (other than the main branch of the github).  Users would be able to submit pull requests to add files, and the admins (primarily me, presumably) would be responsible for verifying it's not spam, and making sure it fits into the repo correctly.

2) It could just be a page in the existing npp-usermanual repo (or page section).  Part of me likes that idea, because it uses the existing repo, and would also be published to the npp-user-manual.org site... but since it makes more sense for each language to be its own file, I'm not sure we want to clutter the npp-user-manual website with that many files.

To implement idea 1, I believe @donho would have to create that empty repo.  After that, I'd be willing to scrape the old web.archive to grab the old UDL files, and start uploading those files as the initial basis for the new repo.

If idea 2 (or some other idea), I'd like comments for how it might be implemented

**Comment by chcg** [comment]
@pryrt Another idea would be that UDLs could be downloaded just like plugins by the pluginAdmin system. PluginManager already had that possibility after the introduction of individual files per UDL.

**Comment by donho** [comment]
> Another idea would be that UDLs could be downloaded just like plugins by the pluginAdmin system. 

Yes, that's what I think when I saw this issue.
But it needs to code it in Notepad++.  I would say we can open a repository to collect UDLs firstly, we need also an list for some UDLs which are stocked outside. User can get them and install them in the mean time. The 2nd step we can code the feature UDL Admin in Notepad++.
What do you think @chcg @pryrt  ?
@chcg

**Comment by cup** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7807

**Comment by pryrt** [comment]
Seems like a good plan to me.  Let me know when the UDL repository is available, and I'll add the link into the usermanual.

Thanks!

**Comment by chcg** [comment]
Example from old pluginManager:

https://github.com/bruderstein/npp-plugins-x64/blob/master/plugins/plugins64.xml#L1371-L1393

**Comment by rddim** [comment]
Oh, yes, this is from my repo. I had forgotten about it. I have a new one with the new folder structure here: https://github.com/rddim/npp-udl which contain two UDLs. The old one will be deleted after 6 months.

**Comment by donho** [comment]
@rddim So may I use your your 2 UDL for initializing the new repo ?
https://github.com/notepad-plus-plus/userDefinedLanguages

**Comment by rddim** [comment]
@donho Yes, you can. But keep in mind that the `LandSurveyPlusPlus.npp.udl.xml` UDL is relevant only for the Bulgarian land surveyors.

**Comment by donho** [comment]
@rddim 
Why there are 3 Autocad UDLs?

**Comment by rddim** [comment]
@donho Because of the different files type - one for `*.scr`, one for `*.lin` and one for `*.pat` and `*.shp`. In 2014, when I start to learn how to create UDL I didn't think to create one file that support different types. But now with your question I try to make only one :)

**Comment by rddim** [comment]
@donho I'm ready with the `only one` combined file, but I will publish it when the discussion about the filenames is finished.
