### ISSUE TITLE
Improve Document Switcher documentation

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#628]
The current extent of the Document Switcher documentation seems to be:

_☐ Enable: Hitting Ctrl+TAB will allow you to easily switch through all the open documents._

Some suggested changes:

"Hitting" sounds rather violent; perhaps it could be "Pressing"?

Also, it needs further discussion, on these points (ideas expressed are rather ad-hoc, and probably need the user manual moderator's spin on the wording):

* The idea behind usage is that one would hold the Ctrl key and then press+release the Tab key.  This gets the Doc Switcher on screen in the form of a yellow-backgrounded popup showing the current tab set for the view (or a subset if there are too many tabs).  Initially the name of the tab to the right of the currently-active tab will be bolded, with boldness indicating which tab will be made activate when all keys have been released.  With the Doc Switcher on screen, repeated press+release of the Tab key will move the bold highlight downward on screen to the next tab name in the list.  When the desired tab appears bolded, release all keys to make the bolded tab active in the editor.

* If the bottom-most entry is reached and another Tab press+release is executed, the topmost entry will be bolded, i.e., the highlight will wrap around to the first entry in the list (or, if the list was too long to entirely be displayed, the next entry will be made visible and will become bold.

* Adding Shift in such that both Ctrl and Shift are the held keys will cause the bold highlight to move to the previous list entry rather than the next.

* The Doc Switcher functionality can also be achieved using the mouse alone:  Right-click in the editing area for a tab and hold it, then begin scrolling the mouse wheel (in either direction).

**Comment by pryrt** [comment]
@alankilborn , let me know what you think of the **Document Switcher** section on the new "User Interface" page

**Comment by alankilborn** [comment]
>let me know what you think of the Document Switcher section on the new "User Interface" page

First of all, awesome job with the Doc Switcher changes and all the others grouped with it!
Second, I had some comments directly in the change...
