### ISSUE TITLE
As of Notepad++ 8.6.5, the Shortcut Mapper will filter shortcuts by words in the filter box

### ISSUE THREAD

**Issue by molsonkiko** [notepad-plus-plus/npp-usermanual#645]
If someone doesn't like the new functionality, they have [this commit I authored to blame](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2adf71213552115632093232a2ebf8e6abfdd8aa).

In any case, I would suggest that the user manual include some subset of the following, to explain how the shortcut mapper now filters shortcuts:

### How the shortcut mapper filter works (Notepad++ 8.6.5+ only)

__1. Consider a plugin command named "do thing" with plugin "BlahLint" and keycombo "Alt+G"__
    Filters that match:
    - "lint do +" (the "+" is matched by "alt+g")
    - "+G thing blah"
    Filters that *do not* match:
    - "lint foo +g" ("foo" is not in any field)
    - "thing alt quz" ("quz" is not in any field)
__2. Consider a Scintilla command named "foo baz" with keycombos "Alt+H or Ctrl+Shift+Q"__
    Filters that match:
    - "baz or" (the "or" is matched by "Alt+H or Ctrl+Shift+Q")
    - "+q foo"
    Filters that *do not* match:
    - "+q +z" ("+z" is not in any field)
    - "quz"
    - "baz Tab" ("tab" is not in any field)
__3. Consider any other type of command named "cute kitty" with keycombo "Alt+K"__
    Filters that match:
    - "alt k" matches ("k" is matched by "kitty" *and* "alt+k")
    - "kit alt"
    Filters that *do not* match:
    - "cute q" ("q" is not in any field)
    - "z kit" ("z" is not in any field)

**Comment by rdipardo** [comment]
I read this whole thing just to find out what was missing from the issue title: "As of Notepad++ __*8.6.5*__ . . ."

**Comment by molsonkiko** [comment]
> I read this whole thing just to find out what was missing from the issue title: "As of Notepad++ **_8.6.5_** . . ."

Good catch, fixed.

**Comment by alankilborn** [comment]
> If someone doesn't like the new functionality

Aside from the fact that people will always find something to complain about, I can't see any reason not to like the new functionality.

**Comment by pryrt** [comment]
This won't be added until 8.6.5 is in Release Candidate.

However, this is my suggested implementation:

> Starting in v8.6.5, when you type multiple space-separated character sequences ("tokens") as your **Filter**, it will try to match each token separately, in the same entry.  When filtering, it will search all the displayed fields for the dialog (whether in "Name" or "Shortcut" or "Plugin" column).  All of the tokens must be matched somewhere in the entry, but they can be in any order.  Some examples:
> 
> **Shortcut Mapper > Plugin commands**
> | Name | Shortcut | Plugin | Filter | Match?
> |------|----------|--------|--------|--------
> | do thing | <kbd>Alt+G</kbd> | BlahLint | `lint do +` | Yes (`lint` from Plugin, `do` from Name, `+` from Shortcut)
> | do thing | <kbd>Alt+G</kbd> | BlahLint | `+G thing blah` | Yes (`+G` from Shortcut, `thing` from Name, `blah` from Plugin)
> | do thing | <kbd>Alt+G</kbd> | BlahLint | `lint foo +G` | No (`foo` not in any field, despite `lint` in Plugin and `+G` in Shortcut)
> 
> **Shortcut Mapper > Scintilla commands**
> 
> | Name | Shortcut | Filter | Match?
> |------|----------|--------|--------
> | foo baz | <kbd>Alt+H</kbd> or <kbd>Ctrl+Shift+Q</kbd> | `baz or` | Yes (`baz` from Name, `or` from Shorcut)
> | foo baz | <kbd>Alt+H</kbd> or <kbd>Ctrl+Shift+Q</kbd> | `+q foo` | Yes (`+q` from Shortcut, `foo` from Name)
> | foo baz | <kbd>Alt+H</kbd> or <kbd>Ctrl+Shift+Q</kbd> | `+q +z` | No (`+z` not in any field, despite `+q` in Shortcut)
> | foo baz | <kbd>Alt+H</kbd> or <kbd>Ctrl+Shift+Q</kbd> | `baz tab` | No (`tab` not in any field, despite `baz` in Name)
> 
> **Shortcut Mapper > Main menu** or **Macros** or **Run commands**
> 
> | Name | Shortcut | Filter | Match?
> |------|----------|--------|--------
> | cute kitty | <kbd>Alt+K</kbd> | `alt k` | Yes (`alt` from Shortcut, `k` in both Name and Shortcut)
> | cute kitty | <kbd>Alt+K</kbd> | `kit alt` | Yes (`kit` from Name, `alt` from Shortcut)
> | cute kitty | <kbd>Alt+K</kbd> | `cute q` | No (`q` not in any field, despite `cute` being in Name)
> 

@molsonkiko, Your examples didn't make one thing clear to me: will it also search the **Category** column on the **Main menu**?

**Comment by molsonkiko** [comment]
The Category field of Main Menu commands will not be considered, though I
could easily submit another PR to change that. I noticed that behavior as
well, but I didn't bother to fix that as well because I wasn't sure if it
was intended.

**Comment by pryrt** [comment]
> The Category field of Main Menu commands will not be considered

That's fine.  I just wanted to make sure I understood.
