### ISSUE TITLE
Prefs page section needs reordering

### ISSUE THREAD

**Issue by TBugReporter** [notepad-plus-plus/npp-usermanual#661]
In the process of rebuilding my preferences, I've been reviewing the relevant doc page, and got confused by one section.  "Margins/Border/Edge" lists its subsections as "Fold Margin Style, Border Width, Vertical Edge Settings, Line Number, Padding, Change History", in that order, but this isn't the order in the program.

I did a pull and made the change there, but I've never used GitHub for anything other than forum messages before, and I'm not sure what else I need to do to get this merged.  Please advise.

**Comment by pryrt** [comment]
> I'm not sure what else I need to do to get this merged. Please advise.

Create a Pull Request from your fork.  (There should be a button that says something like "Contribute", and if you pull it down, there will be a "create a pull request" action.  My terminology is from memory, because I don't have a branch with active changes to look at right now.)

**Comment by TBugReporter** [comment]
> Create a Pull Request from your fork.

I thought that was what I did.  See <https://github.com/TBugReporter/npp-usermanual/blob/master/content/docs/preferences.md>.  I have a few other changes of this nature, but I haven't made them yet (not even in my copy) because I don't know if I should do that before you deal with the first change.

**Comment by pryrt** [comment]
> I thought that was what I did

No pull request has been created by you in this repo.  I do not know what went wrong with your attempt.

> I have a few other changes of this nature

If they are all in the same section, make it one PR.  If they are in different areas, separate PRs are a good idea.
