### ISSUE TITLE
Document open-the-copy functionality for Save a Copy As

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#692]
new (second) bullet point text:

Normally during execution of this command, the new file created is not opened into a Notepad++ editing tab.  To open the new file as part of the process, hold down the Shift key while pressing the Save button in the SaveAs dialog.

---

typo in first bullet point text:  `back` should be `backup`?:

"The new file will be saved, but Notepad++ will continue to work with the document associated with the original filename. So this action effectively creates a backup of the file, but allows you to continue working with the previous file, whereas Save As uses the original as the `back` and allows you to keep working with the new file."

---

refs:

* https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfe27cc8602d510abc9dc12545dadae432614bd6
* https://github.com/notepad-plus-plus/notepad-plus-plus/pull/15476
* https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11861

**Comment by pryrt** [comment]
I'll fix the typo now.  I'll hold off on the new functionality until the RC is announced.
