### ISSUE TITLE
Improve documentation for close-related plugin messages

### ISSUE THREAD

**Issue by alankilborn** [notepad-plus-plus/npp-usermanual#719]
Comment: The docs for plugin communication messages in general is "not great". One could spend a lot of time improving this section of the UM wholesale, but maybe this is not a great use of time. Perhaps better is if the section is improved a bit at a time.
I wanted to open this issue as a starting point for discussion.  If it is generally liked, I could certainly propose exact new documentation text.

---

The scenario: Recently I was scripting something that I wanted to have happen when a file/tab is closed.

My starting point was [NPPN_FILECLOSED](https://npp-user-manual.org/docs/plugin-communication/#1005nppn_fileclosed) which currently states: _To notify plugins that the current file is about to be closed_.
Problems with that:
* It isn't necessarily a true statement (consider the case of a _Close All_)
* I was hoping to get the name/path of the file from the notification, all I can get is a `BufferID` -- as documented -- but that id is sort of meaningless in terms of using it to obtain the name/path since the id is invalid after the file/tab is closed.  This is technically not a problem, but it is rather "non obvious"
* In the case of a cloned document, when a _Close_ is issued on the file/tab, the `BufferID` provided _IS_ valid (because one copy of the clone remains)

Because I needed the name/path of the file, I next went to [NPPN_FILEBEFORECLOSE](https://npp-user-manual.org/docs/plugin-communication/#1003nppn_filebeforeclose) which currently states: _To notify plugins that the current file is about to be closed_
Problems:
* Again, it isn't necessarily a true statement (consider the case of a _Close All_)
* (not a true problem but) It might be nice if it were pointed out here that the caller can obtain the name/path of the tab about to close by using the BufferID and calling [NPPM_GETFULLPATHFROMBUFFERID](https://npp-user-manual.org/docs/plugin-communication/#2082nppm_getfullpathfrombufferid) -- which was what I needed to do for my situation
* (not a true problem but) It might be reasonable to point out that this notification seems to exist so that the user can do something while there is a valid BufferID, and that by the time NPPN_FILECLOSED occurs it is (probably) too late

I don't know...maybe I'm being picky.  But I'm always out to improve things that could be improved.  :-)

---

Here's a PythonScript3 one-liner that I found useful during experimentation.  Copy the line and paste into PS3's Console window `>>>` prompt and press Enter:

```py
from Npp import *; notepad.callback(lambda args: print(f'FILEBEFORECLOSE:\n {args=}\n {notepad.getCurrentFilename()=}\n {notepad.getBufferFilename(args["bufferID"])=}\n {notepad.getBufferFilename(notepad.getCurrentBufferID())=}'), [NOTIFICATION.FILEBEFORECLOSE]); notepad.callback(lambda args: print(f'FILECLOSED:\n {args=}\n {notepad.getCurrentFilename()=}\n {notepad.getBufferFilename(args["bufferID"])=}\n {notepad.getBufferFilename(notepad.getCurrentBufferID())=}'), [NOTIFICATION.FILECLOSED])
```

This will generate console output such as the following when file/tabs are closed:

```txt
FILEBEFORECLOSE:
 args={'code': 1003, 'bufferID': 2251062323488}
 notepad.getCurrentFilename()='new 2'
 notepad.getBufferFilename(args["bufferID"])='new 2'
 notepad.getBufferFilename(notepad.getCurrentBufferID())='new 2'
FILECLOSED:
 args={'code': 1005, 'bufferID': 2251062323488}
 notepad.getCurrentFilename()='new 1'
 notepad.getBufferFilename(args["bufferID"])=''
 notepad.getBufferFilename(notepad.getCurrentBufferID())='new 1'
```

Note that in the example, for the `FILECLOSED` output, the `bufferID` of the closed file is invalid causing ` notepad.getBufferFilename(args["bufferID"])` to return an empty string.

**Comment by alankilborn** [comment]
I don't like to do PRs for the docs any longer...because I don't know all the nuances of formatting, referencing other sections, etc. I'd rather just propose some text, and, if it is liked, have it adopted with any embellishments the manual maintainer likes.  :-)

**Comment by alankilborn** [comment]
>Actually, that notification desc says is just closed.

Sorry, copy+paste+forgetToChange error.  :-(

**Comment by alankilborn** [comment]
>any useful information passed into NPPN_FILECLOSED, nor that there's any meaningful action that a plugin can take when given that message, unless the plugin is doing its own tracking by bufferID

Well, what I'm doing in my script is obtaining the tab's path in FILEBEFORECLOSE and then in FILECLOSED I'm doing something with that path (it's important that I wait until the file is actually closed before doing my thing).  Also in FILECLOSED, I'm detecting if the path is a cloned file.  So, I suppose there are some uses for it.

**Comment by alankilborn** [comment]
>that those notifications should say something like To notify plugins that the indicated file is just closed rather than current file.

FILEBEFORECLOSE could say that.  I'm not so sure about FILECLOSED, because there's no "indicated file" there (if used standalone).

**Comment by pryrt** [comment]
> Well, what I'm doing in my script is obtaining the tab's path in FILEBEFORECLOSE and then in FILECLOSED I'm doing something with that path (it's important that I wait until the file is actually closed before doing my thing). Also in FILECLOSED, I'm detecting if the path is a cloned file. So, I suppose there are some uses for it.

But you are effectively doing tracking by bufferID by doing the FILEBEFORECLOSE to get the name then FILECLOSED to process the name.

**Comment by pryrt** [comment]
> > that those notifications should say something like To notify plugins that the indicated file is just closed rather than current file.
> 
> FILEBEFORECLOSE could say that. I'm not so sure about FILECLOSED, because there's no "indicated file" there (if used standalone).

By "indicated file" I meant "the file that was at one time indicated by the bufferID, which for FILECLOSED is now pointing to nothing and useless".  I guess I should have said "indicated bufferID" instead of "indicated file", because that's true whether the buffer referenced by that bufferID is still valid or not.
