### ISSUE TITLE
Add a hidden anchor for the npp updater's Safety Delay

### ISSUE THREAD

**Issue by mkupper** [notepad-plus-plus/npp-usermanual#735]
When someone does `? / Update Notepad++` from Notepad++ it starts WinGUp.exe which checks the version of Notepad++ the person is running against what is available from the Notepad++ web site. If no new version is available then WinGUp display a dialog box:

``` txt
No update is available
or the newest version is not triggered yet for updating (more info)

Go to the download page to update Notepad++ manually.
```

The string "`more info`" in that dialog box links to https://npp-user-manual.org/docs/upgrading/#new-version-available-but-auto-updater-find-nothing

The problem is that there is no anchor for `#new-version-available-but-auto-updater-find-nothing`

A possible fix would be to add a hidden anchor in the user manual for that will take people to the "No New Version Found: Safety Delay" section at https://npp-user-manual.org/docs/upgrading/#no-new-version-found-safety-delay

If possible, there should also be a hidden comment about that the anchor is used by WinGUp at https://github.com/notepad-plus-plus/wingup/blob/master/src/winmain.cpp line 780
or https://github.com/notepad-plus-plus/wingup/blob/21e375caf17360fb86f757612052d5a785261d96/src/winmain.cpp#L780 if you want to use a permalink to that line.

The issue came about from this forum thread: https://community.notepad-plus-plus.org/topic/26434/update-failure/5

**Comment by pryrt** [comment]
> the problem is that there is no anchor for `#new-version-available-but-auto-updater-find-nothing`

I did some rephrasing, including to that header, a few years back.  I guess I never knew wingup was linking to the old phrasing of that header.  I'll fix it.
