### ISSUE TITLE
Tradition Chinese Translation Error

### ISSUE THREAD

**Issue by ChaoTingChen** [notepad-plus-plus/npp-usermanual#76]
when right click of open files,the "Full File Path to Calipboard" is mapping to Chinese "將資料夾路徑複製到剪貼簿" which is not correct, it's confused of "Current Dir.Path to Calipboard"
https://imgur.com/AppJI1G
version : v7.8.4 (32 bit)

**Comment by donho** [comment]
It should be repported here:
https://github.com/notepad-plus-plus/notepad-plus-plus

Fixed:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2f9f395efff06e210d7adc2637e2d157cd53742a
