### ISSUE TITLE
website certificate expired

### ISSUE THREAD

**Issue by brkdncr** [notepad-plus-plus/npp-usermanual#80]
It looks like at least one of the web servers has an expired certificate:
npp-user-manual.org
12/1/2019, 6:42:08 AM (Pacific Daylight Time)
2/29/2020, 6:42:08 AM (Pacific Daylight Time)
03:F5:03:BF:E4:67:51:18:33:6D:C5:8D:31:76:58:18:D3:A7

I was able to see it a few times just by reloading the page but it seems to be occuring less than 1 in 5 times.

![2020-04-09 11_03_56-Window](https://user-images.githubusercontent.com/29586717/78926475-fafc4d80-7a51-11ea-978b-cd1b0a7dcc57.png)
![2020-04-09 11_03_44-Window](https://user-images.githubusercontent.com/29586717/78926478-fc2d7a80-7a51-11ea-8cd9-02a00e999d9a.png)
![2020-04-09 11_03_28-Window](https://user-images.githubusercontent.com/29586717/78926480-fcc61100-7a51-11ea-935f-e953f54b124d.png)

**Comment by donho** [comment]
I've go no issue on https://npp-user-manual.org/
Has anyone such issue?

**Comment by chcg** [comment]
It is working for me. The certificate is valid from 2.4.2020 to 1.7.2020 with Firefox 75.0.

**Comment by donho** [comment]
I guess it's an issue of user's environment.

**Comment by brkdncr** [comment]
I added screenshots of the certificate being displayed.  This was being
retrieved from the server side, i wouldn’t be able to see these
certificates any other way.  I suspect this is/was an issue with any
caching service such as cloudfare.  After a few minutes i wasn’t able to
reproduce the issue.

**Comment by mnh48** [comment]
I'm here just to report that it's happening for me as well
It's the same on both my PC and mobile phone
across all browsers I have, including in incognito/private mode

on vivaldi (ver 3.4.2066.86) on PC (my main browser):
![image](https://user-images.githubusercontent.com/12217018/98445262-b5237700-2151-11eb-981f-92cb5c3e9ba1.png)

on firefox (ver 82.0.2) on PC:
![image](https://user-images.githubusercontent.com/12217018/98447063-038a4300-215d-11eb-96e6-200b2571a056.png)

on chrome (ver 86.0.4240.185) on mobile:
![Screenshot_20201107-233602_Chrome_scaleddown](https://user-images.githubusercontent.com/12217018/98446227-041fdb00-2157-11eb-9c31-97ee5ce4f7c0.jpg)

**Comment by celtic-coder** [comment]
There are three separate servers hosting this site. One of them is not setup correctly (as per https://www.ssllabs.com/ssltest/analyze.html?d=npp-user-manual.org):

![image](https://user-images.githubusercontent.com/11787866/98448521-75926600-2124-11eb-885a-3bd16dc5d261.png)

The certificate on that server ([2a02:4780:8:362:0:2b37:d7f5:3](https://www.ssllabs.com/ssltest/analyze.html?d=npp%2duser%2dmanual.org&s=2a02%3a4780%3a8%3a362%3a0%3a2b37%3ad7f5%3a3)) expired 9 months ago:

**Comment by donho** [comment]
@celtic-coder 
> There are three separate servers hosting this site. 

https://npp-user-manual.org/ is hosted on only one server. I'm sure about it.

**Comment by celtic-coder** [comment]
Hi Don (@donho),

You are correct. I should have said three IP addresses. 

I don't understand why there is an issue with one of the IPv6 addresses. Both [2a02:4780:8:362:0:2b37:d7f5:3 ](https://www.ultratools.com/tools/ipv6InfoResult?ipAddress=2a02%3A4780%3A8%3A362%3A0%3A2b37%3Ad7f5%3A3) and [2a02:4780:1:1:0:0:1:920b](https://www.ultratools.com/tools/ipv6InfoResult?ipAddress=2a02%3A4780%3A1%3A1%3A0%3A0%3A1%3A920b) appear to be valid. 

[Both](https://mxtoolbox.com/SuperTool.aspx?action=aaaa%3anpp-user-manual.org&run=toolpage) are associated with **npp-user-manual.org**.  However, [Netcraft](https://sitereport.netcraft.com/?url=https%3A%2F%2Fnpp-user-manual.org) only lists the 2a02:4780:1:1:0:0:1:920b IPv6 address. I don't know if this is of any significance. Especially as this is the one without error in the SSLabs report.

Going back to the report, the main page gives the following warning:

![image](https://user-images.githubusercontent.com/11787866/98484810-dba4e900-2209-11eb-9d44-cc290fff2c8c.png)

The only thing I could find is this article, [SSL Inconsistent server configuration](https://www.digitalocean.com/community/questions/ssl-inconsistent-server-configuration), where the error is also on an Ubuntu server. Might this be an area to explore, perhaps?

Kind Regards,
Liam
