### ISSUE TITLE
small minor mistake with the documentation

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/npp-usermanual#83]
[:name:] should've been [[:name:]] under this description:
![image](https://user-images.githubusercontent.com/13095760/80548988-0a542400-898a-11ea-8b29-60482a6f53a6.png)
Found here: https://npp-user-manual.org/docs/searching/

Never explained that that whole thing alone had to be in brackets.

**Comment by GhbSmwc** [comment]
thanks for moving!

**Comment by pryrt** [comment]
@GhbSmwc,  the phrase "which must be part of a character class" was meant to convey the requirement that `[:name:]` had to be inside a character class.  But it was obviously not clear enough, so I've added more discussion of that requirement, including examples.
