### ISSUE TITLE
Documentation License for usermanual

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/npp-usermanual#99]
As brought up in #96 discussion: Should we choose a documentation license?  If so, which should we choose?

* [GNU Free Documentation License (GFDL)](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) ([official text](https://gnu.org/licenses/fdl.html))
* One of the [Creative Commons licenses](https://en.wikipedia.org/wiki/Creative_Commons_license)
* _Your Favorite Goes here_

**Comment by pryrt** [comment]
I have no preference or even really experience on doc licenses, so just listed the ones I'd heard of.

**Comment by donho** [comment]
Since Notepad++ is GPL, GFDL +1.
